import { CharacterBuilder } from '../Character.js';
import { AffinityVector } from '../AffinityVector.js';
import { item } from '../links.js';
export let potentialCharacters = []

let OTP = 20;
let CRITICAL = 15;
let VERY = 10;
let SOME = 5;
let NONE = 0;
let NEGATIVE = -5;
let VERY_NEGATIVE = -10;


potentialCharacters.push(
    new CharacterBuilder()
    .setBuildName('The Dancer')
    .setMainClass('Bard')
    .setSubClass('College of Dance')
    .setLevels(11)
    .setMultiClass('Monk')
    .setMultiClassSubClass('Warrior of Mercy')
    .setMultiClassLevels(5)
    .setHasPlaytestMaterial(true)
    .setHasHomebrewMaterial(false)
    .setBuildDraw('The Dancer is a very unique build that is a mix of a support and a melee DPS. It\'s strength lies in its ability to move around the battlefield quickly and efficiently, providing the most amount of Bardic Inspiration dice possible for any Bard subclass all while being able to use it\'s action to make powerful unarmed attacks.')
    .setNarritiveDescription('You are as nimble as they come. In combat you are seen weaving through the battlefield with unparalleled speed. One moment healing your wounded backline and the next unleashing a flurry of blows upon the backline of the enemy. As you move your voice rises in an inspiring chant, encouraging your comrades and boosting their morale. Your bardic magic filling the air. Your allies are invincible with you by their side and your enemies fall at your hands. All this, and you don\'t even wield weapons or armor, it just wouldn\'t be fair.')
    .setMainClassGameplayDescription('Your core gameplay loop revolves around Agile Strikes and Font of Inspiration. Font of Inspiration allows you to use Bardic Inspiration every turn without running out of uses while Agile Strikes allows these Bardic Inspiration uses to also grant you a free unarmed attack. Using your bardic inspiration as a bonus action every turn will allow you to constantly hand out the die while also dishing out punches to the enemies, all without using your action which can be saved for a powerful spell or more punches.')
    .setMultiClassGameplayDescription('Your monk levels enhance your free unarmed attacks as well as your movement: making you even more slippery and able to dash around the battle field to wherever you\'re needed.')
    .setMultiClassSubClassGameplayDescription('Your monk subclass allows you to heal with just a touch, giving you another resource for healing if you are low on spell slots. Unarmored Defense, Inspiring Movement, Tandem Footwork, and Leading Evasion allow you and your party to move quickly; making them less likely to take damage, be higher on the turn order, and to stay out of danger.')
    .setFeats('Take +2 DEX for your first two ASIs to max out your DEX. Then take the Mobile feat to further enhance your movement and to make it easier to get in and out of combat. At 12th level Bard you will get another ASI which I would use to take the Inspiring Leader feat to give your party even more temporary hit points. Instead of Inspiring Leader or Mobile you could also take a half-feat that gives +1 CHA and a small bonus, such as Actor or Diplomat and/or take the +2 CHA/WIS ASI if you feel like your bard spells or stunning strikes are not landing enough.')
    .setRace('Half-Elf - The +2 CHA and +1 to two other stats (WIS/DEX) is perfect for this very MAD build. You do not need the extra CHA (since it puts you at an odd number) unless you plan on taking a CHA half-feat so Human is also a good choice.')
    .setAttributes('STR: 8, DEX: 16, CON: 8, INT: 8, WIS: 16, CHA: 17')
    .setBackground('Not much is known about your parents, but you were raised by a group of monks who taught you the ways of the warrior. You were always a natural performer and your love of life and dance led you away from the joyless life of a monk and into the world of the bard. However, you never forgot the lessons of your youth and, with them, you created a new fighting style that combined the grace of a dancer with the power of a monk. You used the powerful new style as you traveled the world, performing and fighting for those in need. You are a beacon of hope and joy, and your enemies will never forget the day they crossed you. Your prowess on the battlefield is known far and wide, and now young bards sing songs of your exploits. Your travels led you to The Sword Coast, where you currently reside.')
    .setMagicItemsByTier(0, item('Rhythm Maker\'s Drum'))
    .setMagicItemsByTier(1, item('Amulet of Health'))
    .setMagicItemsByTier(2, item('Eldritch Claw Tattoo') + ' AND ' + item('Insignia of Claws'))
                                // 16
    .setRecommendedSpellsByTier(1, ['Cure Wounds', 'Dissonant Whispers', 'Tasha\'s Hideous Laughter', 'Silvery Barbs', 'Faerie Fire']) // 6
    .setRecommendedSpellsByTier(2, ['Aid', 'Gift of Gab', 'Kinetic Jaunt']) // 3
    .setRecommendedSpellsByTier(3, ['Catnap', 'Hypnotic Pattern', 'Leomund\'s Tiny Hut']) // 3
    .setRecommendedSpellsByTier(4, [])
    .setRecommendedSpellsByTier(5, ['Greater Restoration']) // 1
    .setRecommendedSpellsNotes('These core spells only account for 13 of the 16 spells you can have prepared so you may pick a few of your favorite spells and add them to the list. Be warned Bards cannot change their spell list at will so choose wisely.')
    .setOtherNotes('')
    .addAffinityVector(new AffinityVector('TANK', NONE))
    .addAffinityVector(new AffinityVector('MELEE_DPS', VERY))
    .addAffinityVector(new AffinityVector('RANGED_DPS', NONE))
    .addAffinityVector(new AffinityVector('CASTER_DPS', NONE))
    .addAffinityVector(new AffinityVector('SUPPORT', CRITICAL))
    .addAffinityVector(new AffinityVector('POWER', SOME))
    .addAffinityVector(new AffinityVector('UNIQUENESS', SOME))
    .addAffinityVector(new AffinityVector('EXPERT', SOME))
    .addAffinityVector(new AffinityVector('VERSATILITY', SOME))
    .addAffinityVector(new AffinityVector('MULTICLASS', VERY))
    .addAffinityVector(new AffinityVector('NIMBLE', SOME))
    .addAffinityVector(new AffinityVector('STALWART', NONE))
    .addAffinityVector(new AffinityVector('FIELD', SOME))
    .addAffinityVector(new AffinityVector('MAGIC', SOME))
    .addAffinityVector(new AffinityVector('DEFENCE', SOME))
    .addAffinityVector(new AffinityVector('NOVA', NEGATIVE))
    .addAffinityVector(new AffinityVector('BUFF', CRITICAL))
    .addAffinityVector(new AffinityVector('DEBUFF', SOME))
    .addAffinityVector(new AffinityVector('HEAL', NONE))
    .addAffinityVector(new AffinityVector('SHIELD', NONE))
    .addAffinityVector(new AffinityVector('SAVE', OTP))
    .addAffinityVector(new AffinityVector('AOE', SOME))
    .addAffinityVector(new AffinityVector('ST', VERY))
    .build()
);

potentialCharacters.push(
    new CharacterBuilder()
    .setBuildName('The Siren')
    .setMainClass('Bard')
    .setSubClass('College of Lore')
    .setLevels(15)
    .setMultiClass('Cleric')
    .setMultiClassSubClass('Peace Domain')
    .setMultiClassLevels(1)
    .setHasPlaytestMaterial(true)
    .setHasHomebrewMaterial(false)
    .setBuildDraw('The Siren is a fun build designed to make the most of the Bard\'s ability to learn spells from any class. Having bardic inspiration (d12 at this level), bless, and your Peace domain ability all at once is the foundation of your support powers which only requires a single prepared spell. Apart from that, you can customize your spell list to be whatever you like: either a variety of support spells such as are recommended below, or even take all damage spells and just provide the passive support from your bardic inspiration, bless, and Peace domain ability.')
    .setNarritiveDescription('Your words drip with power, your every syllable unnerving enemies and empowering friends.  Chanting your arcane verse you unleash the culmination of your thorough magical studies. Through a lifelong commitment to knowledge you have amassed the ability to cast almost any spell and you wield this knowledge as a weapon and a shield, your knowledge of the arcane granting you a diverse arsenal of spells to bring to bear in any combat.')
    .setMainClassGameplayDescription('Through Magical Secrets and Additional Magical Secrets, you have access to a wide variety of spells, allowing you to adapt to any situation. Your spellcasting is your primary focus, and you have amongst the largest amount of prepared spells as well as access to all spells in the game. The power and draw of this character is that the only limit to your spellcasting is your imagination.')
    .setMultiClassGameplayDescription('You have lots of additional utility from Song of Rest, Countercharm, and Peerless Skill. You can also use your Bardic Inspiration to help your allies with their saving throws.')
    .setMultiClassSubClassGameplayDescription('Your cleric dip gives you access to the Peace Domain\'s Emboldening Bond to further buff allies and medium armor proficiency to increase your survivability.')
    .setFeats('Heavily Armored, Resilient(CON), and +1 CON/+1 CHA should be your first 3 ASIs. Next level you can take Inspiring Leader or +2 CHA.')
    .setRace('Aasimar for the extra healing option and flight. Sirens were canonically part woman and part bird so the winged/angelic Aasimar fit the theme and backstory of this character well. Pick which type of Aasimar based on what alignment you want to play. Protector Aasimar is the best for this build, but Fallen and Scourge Aasimar work as well.')
    .setAttributes('STR: 8, DEX: 8, CON: 16, INT: 10, WIS: 14, CHA: 17')
    .setBackground('From a young age you recognized the power of words. Even before your celestial heritage began to overpower your human one, you found yourself manipulating the humans to do your will, even your own earthly parents. When you were still young you decided to leave home to study as a Bard, wanting to learn more about how to use your powers to inspire and control others. Your parents, of course, would not let a young child leave to go study. However, through your divine lineage and knack for manipulation you convinced your parents that it was not only best for you, but best for them as well. And so you left, traveling across the world to study at one of the most renowned Bardic Colleges. During your travels, you wanted for little as you further used your voice to manipulate others. It was at the Bardic College that you first began to learn that your words could control much more than just people but also objects, the elements, and even the laws of reality itself. Your lust for learning to control others extended to magic and so began your life-long journey to learn everything there is to know about magic. Through your interactions with the Lore Bards at the college, you also began to show a lust for all forms of knowledge. Though you seldom care for the whimsies and politics of man, preferring instead to focus on your own pursuits, you are often called to appear before courts, classrooms, festivals, and affairs of state as you are widely regarded as one of the most intelligent beings the world has to offer.')
    .setMagicItemsByTier(0, item('Rhythm Maker\'s Drum'))
    .setMagicItemsByTier(1, item('Reveler\'s Concertina'))
    .setMagicItemsByTier(2, item('Mithral Armor') + '(Plate) AND ' + item('Pearl of Power') + ' AND buy a +1 Shield in the first session.')
                                    // 6 10+10 or 20+4 - 6 16
    .setRecommendedSpellsByTier(1, ['Bless - Cleric', 'Healing Word - Cleric', 'Cure Wounds - Cleric', 'Detect Magic - Cleric', 'Dissonant Whispers', 'Tasha\'s Hideous Laughter']) // 2
    .setRecommendedSpellsByTier(2, ['Aid', 'Lesser Restoration']) // 2
    .setRecommendedSpellsByTier(3, ['Leomund\'s Tiny Hut', 'Mass Healing Word', 'Revivify - Magical Secrets']) // 2 1
    .setRecommendedSpellsByTier(4, ['Raulothim\'s Psychic Lance']) // 1
    .setRecommendedSpellsByTier(5, ['Greater Restoration', 'Mass Cure Wounds']) // 2
    .setRecommendedSpellsByTier(6, ['Otto\'s Irresistible Dance*', 'Heroes\' Feast']) // 1
    .setRecommendedSpellsByTier(7, [])
    .setRecommendedSpellsByTier(8, ['Glibness', 'Maze - Magical Secrets']) // 1 1
    .setRecommendedSpellsNotes('Through Cleric, Bard, Magical Secrets, and Magical Discoveries you get 4 (1st level) Cleric spells, 8 Bard-only spells and 12 spells from any list (including Bard). This list of recommended spells has 4 cleric spells, 11 bard spells, and 2 spells from non-bard spell lists. The recommended spells are not mandatory but are all very strong choices and leave you pleanty of room to customize your spell list as you\'d like. Healing Word and Cure wounds will use your WIS instead of CHA because they are Cleric spells. Feel free to change that if you want that little extra healing.')
    .setOtherNotes('The Cleric dip is almost purely for medium armor proficiency and bless. The Peace Domain synergizes well with the Bard, as it gives a second bless (no concentration) which combined with normal bless and bardic inspiration gives your allies 2d4+1d12 = +11.5(average) to ability checks, attack rolls, and saving throws.')
    .addAffinityVector(new AffinityVector('TANK', NONE))
    .addAffinityVector(new AffinityVector('MELEE_DPS', NONE))
    .addAffinityVector(new AffinityVector('RANGED_DPS', NONE))
    .addAffinityVector(new AffinityVector('CASTER_DPS', VERY))
    .addAffinityVector(new AffinityVector('SUPPORT', CRITICAL))
    .addAffinityVector(new AffinityVector('POWER', SOME))
    .addAffinityVector(new AffinityVector('UNIQUENESS', NONE))
    .addAffinityVector(new AffinityVector('EXPERT', SOME))
    .addAffinityVector(new AffinityVector('VERSATILITY', VERY))
    .addAffinityVector(new AffinityVector('MULTICLASS', VERY_NEGATIVE))
    .addAffinityVector(new AffinityVector('NIMBLE', NONE))
    .addAffinityVector(new AffinityVector('STALWART', NONE))
    .addAffinityVector(new AffinityVector('FIELD', NONE))
    .addAffinityVector(new AffinityVector('MAGIC', VERY))
    .addAffinityVector(new AffinityVector('DEFENCE', NEGATIVE))
    .addAffinityVector(new AffinityVector('NOVA', SOME))
    .addAffinityVector(new AffinityVector('BUFF', CRITICAL))
    .addAffinityVector(new AffinityVector('DEBUFF', SOME))
    .addAffinityVector(new AffinityVector('HEAL', SOME))
    .addAffinityVector(new AffinityVector('SHIELD', NONE))
    .addAffinityVector(new AffinityVector('SAVE', CRITICAL))
    .addAffinityVector(new AffinityVector('AOE', VERY))
    .addAffinityVector(new AffinityVector('ST', SOME))
    .build()
);

potentialCharacters.push(
    new CharacterBuilder()
    .setBuildName('The Healbot')
    .setMainClass('Cleric')
    .setSubClass('Life Domain')
    .setLevels(6)
    .setMultiClass('Druid')
    .setMultiClassSubClass('Circle of Stars')
    .setMultiClassLevels(10)
    .setHasPlaytestMaterial(false)
    .setHasHomebrewMaterial(false)
    .setBuildDraw('This character is a healbot and is optimized for pushing out as much healing as possible. If you want to be the best healer in the game, this is the build for you.')
    .setNarritiveDescription('None can match your healing prowess. Your philosophy is that the best support is the one that heals for the biggest number. You have studied both amongsth the clerics and the druids, taking only the information that would allow you to heal the most. Your lifelong goal is to find an enemy who can actually test your healing abilities. You have yet to find one.')
    .setMainClassGameplayDescription('Life Domain gives you access to heavy armor and two of the few ways in DnD to increase healing: Disciple of Life and Blessed Healer. The Life Domain also allows you to automatically prepare several of your core spells, letting you use your prepared spells for more situational spells. It is good to note that Disciple of Life uniquely gives the healing "Whenever you USE a spell" which allows it to proc multiple times for a single spell slot in cases like goodberries and Aura of Vitality. Blessed Healer, unfortunately has the more common wording "When you CAST a spell".')
    .setMultiClassGameplayDescription('We multiclass into Druid at this point largely for the bonuses from the Circle we take later but also to access a few Druid spells that we would not get as a Cleric. ')
    .setMultiClassSubClassGameplayDescription('Circle of Stars grants you a few new spells and free guiding bolts, which is great, but what we are really here for is Starry Form. Specifically the Chalice form. At 10th level the Chalice grants 2d8 + WIS healing to a creature of your choice whenever you CAST (unfortunately the bad wording again) a healing spell. Even with the bad wording, this is a huge boost to your healing. As an added bonus at 10th level while in Starry Form you can change which form it takes at the start of your turn for free if you determine you don\'t need the healing boost for a few turns.')
    .setFeats('Gift of the Gem Dragon (or any WIS half-feat) and +2 WIS for your first two gets you to 20 WIS. For your third ASI I recommend Tough although proficiency for CON saves through a feat will cut down on how often you are recasting your concentration spells. Note the focus on HP and CON is so that you can cast all of your healing spells on allies and slowly heal yourself up through the contstant self healing from Blessed Healer.')
    .setRace('Tasha\'s Custom Lineage: +2 WIS and the Inspiring Leader feat.')
    .setAttributes('STR: 8, DEX: 14, CON: 8, INT: 12, WIS: 17, CHA: 14')
    .setBackground('Growing up, you displayed a natural affinity for the balance between the divine and natural forces, a gift that did not go unnoticed by the village elders. These elders prophesied that you were The Chosen One, destined to save the village and later the world through your ability to heal the wounded and the sick alike, preventing the onset of Death in those you loved. Your parents, both skilled herbalists, nurtured your innate abilities and encouraged you to explore the mystical connection between the divine and the natural world. Because of your innate gifts, you easily mastered the basics of healing both through divine and natural means. However, though you were a prodigy, you can only get so far on natural talent. When study and dedication became a factor, you began to falter. Your gifts had made you lazy and you began to slack off and soon abandoned your studies altogether, much to the disappointment of your parents, the elders, and the town as a whole. Not long after, the first child fell sick. It never became clear where or how the disease started, but there was never much time to investigate as the sickness spread through your village like wildfire. You worked with the healers, the herbalists (namely your parents), and the village elders to help stop the sickness but it was all in vain. One by one every person in the village became ill, and one by one, they started to die. When hope became lost you spent all of your time at home, trying to prolong the inevitable by tending to yourself and your parents. It was then your parents told you to flee, run to the North and find help, with only one person to tend to you might be able to keep yourself alive long enough to find someone who could help treat you. After a long, tear-filled debate you left. As you traveled north you tested all manner of combinations of plants and spells and prayers to cure yourself until one day you discovered a cure on your own. You rushed home in the vain hope that there would be someone left to save but it was too late. In your grief you realized that had you remained focused on your studies you might have really become the chosen one and saved the village. You vowed never to allow this to happen again and have spent the last twenty years studying all manner of healing in the hopes that you will be ready when the second part of the prophecy comes to pass and the world is threatened and you alone can save it.')
    .setMagicItemsByTier(0, item('Candle of Invocation'))
    .setMagicItemsByTier(1, item('Amulet of Health'))
    .setMagicItemsByTier(2, item('Mithral Armor') + '(plate) AND ' + item('Moon Sickle'))
     // 11 15 - 4 5
    .setRecommendedSpellsByTier(1, ['Guiding Bolt*', 'Bless*', 'Cure Wounds*', 'Goodberry', 'Healing Word', 'Inflict Wounds']) // 2 1
    .setRecommendedSpellsByTier(2, ['Lesser Restoration*', 'Spiritual Weapon*', 'Aid', 'Silence', 'Healing Spirit']) // 2 1
    .setRecommendedSpellsByTier(3, ['Beacon of Hope*', 'Revivify*'])
    .setRecommendedSpellsByTier(4, [])
    .setRecommendedSpellsByTier(5, ['Greater Restoration', 'Mass Cure Wounds', 'Maelstrom']) // 0 3
    .setRecommendedSpellsNotes('These core spells only account of for 9 of the 26 druid/cleric spells you can have prepared. You may pick up a few of your favorite spells and add them to the list.')
    .setOtherNotes('Be warned, against enemies of your level, cantrips or spells that you use on enemies will often result in the enemy dodging or saving against your spells. Focus on healing and buffing allies, which is where you shine and much more difficult for enemies to prevent.')
    .addAffinityVector(new AffinityVector('TANK', NONE))
    .addAffinityVector(new AffinityVector('MELEE_DPS', NONE))
    .addAffinityVector(new AffinityVector('RANGED_DPS', NONE))
    .addAffinityVector(new AffinityVector('CASTER_DPS', SOME))
    .addAffinityVector(new AffinityVector('SUPPORT', OTP))
    .addAffinityVector(new AffinityVector('POWER', SOME))
    .addAffinityVector(new AffinityVector('UNIQUENESS', NONE))
    .addAffinityVector(new AffinityVector('EXPERT', NONE))
    .addAffinityVector(new AffinityVector('VERSATILITY', NONE))
    .addAffinityVector(new AffinityVector('MULTICLASS', SOME))
    .addAffinityVector(new AffinityVector('NIMBLE', NONE))
    .addAffinityVector(new AffinityVector('STALWART', NONE))
    .addAffinityVector(new AffinityVector('FIELD', SOME))
    .addAffinityVector(new AffinityVector('MAGIC', VERY))
    .addAffinityVector(new AffinityVector('DEFENCE', SOME))
    .addAffinityVector(new AffinityVector('NOVA', SOME))
    .addAffinityVector(new AffinityVector('BUFF', SOME))
    .addAffinityVector(new AffinityVector('DEBUFF', SOME))
    .addAffinityVector(new AffinityVector('HEAL', OTP))
    .addAffinityVector(new AffinityVector('SHIELD', SOME))
    .addAffinityVector(new AffinityVector('SAVE', SOME))
    .addAffinityVector(new AffinityVector('AOE', SOME))
    .addAffinityVector(new AffinityVector('ST', VERY))
    .build()
);

potentialCharacters.push(
    new CharacterBuilder()
    .setBuildName('Light in the Darkness')
    .setMainClass('Cleric')
    .setSubClass('Twilight Domain')
    .setLevels(6)
    .setMultiClass('Druid')
    .setMultiClassSubClass('Circle of Stars')
    .setMultiClassLevels(10)
    .setHasPlaytestMaterial(false)
    .setHasHomebrewMaterial(false)
    .setBuildDraw('Similar to The Healbot, this character excels at healing. The critical difference is that The Light in the Darkness provides a lot of temporary hit points to the party PASSIVELY, allowing you some time to cast offensive spells or to catch up on healing. This build is also a bit more versatile than The Healbot, as it can also provide some damage and debuffs to the enemy.')
    .setNarritiveDescription('You are a dark beacon of hope and healing to your allies. You are a master of the stars and the night, and you use your knowledge of the cosmos to heal and shield your allies. You are unmatched in your ability to keep your allies healthy, choosing to focus only on support magic that increases the available health pool of your allies at the expense of all other forms of support.')
    .setMainClassGameplayDescription('Twilight Domain gives you access to heavy armor, some cool (but only useful in niche situations) nightvision mechanics, advantage on initiative rolls, and, last but not least, Twilight Sanctuary: the reason we\'re here. You can use it twice per short rest, it lasts 1 minute (typically the whole combat), and most of the time will give every ally 10 temporary hit points every round. This constant stream of temporary hit points helps you keep most of the party healthy while you focus your single target healing on whoever needs it most.')
    .setMultiClassGameplayDescription('We multiclass into Druid at this point largely for the bonuses from the Circle we take later but also to access a few Druid spells that we would not get as a Cleric. ')
    .setMultiClassSubClassGameplayDescription('Circle of Stars grants you a few new spells and free guiding bolts, which is great, but what we are really here for is Starry Form. Specifically the Chalice form. At 10th level the Chalice grants 2d8 + WIS healing to a creature of your choice whenever you CAST a healing spell. This is a huge boost to your healing. As an added bonus at 10th level while in Starry Form you can change which form it takes at the start of your turn for free if you determine you don\'t need the healing boost for a few turns.')
    .setFeats('+1 WIS/+1 CON and +2 WIS for your first two gets you to 20 WIS. Then take Resilient(CON) to get your CON to 16.')
    .setRace('Tasha\'s Custom Lineage - +2 WIS and the Inspiring Leader feat.')
    .setAttributes('STR: 8, DEX: 12, CON: 14, INT: 10, WIS: 17, CHA: 13')
    .setBackground('In the forgotten realms of Eldrath, where shadows danced upon ancient ruins and the whispers of forgotten deities echoed through the night, you first emerged. Born into a secluded village nestled between the edge of the Twilight Forest and the Whispering Peaks, you were marked by destiny from the moment of your birth. Your parents, devoted followers of the Twilight domain, recognized the celestial alignment that bathed you in a soft, otherworldly glow. As you grew, it became evident that your connection to the darkness was extraordinary.Your path diverged as you discovered your innate affinity for the divine and the natural world. Tragedy struck when Eldrath was threatened by an encroaching darkness that seemed to devour all light in its path. Your village was not spared, and your parents perished defending their home. In the aftermath, you felt an urgent calling from both the divine and natural realms, a beckoning to restore balance and push back the encroaching shadows. Seeking answers, you embarked on a pilgrimage to the sacred Starlight Grove, where ancient celestial beings and primal spirits converged. It was here that you encountered the Circle of Stars druids, wise keepers of cosmic secrets and guardians of the delicate balance between light and dark. Under their guidance, you honed your druidic abilities, learning to channel the power of the stars to illuminate the darkest corners of Eldrath. They taught you that the darkness was not to be feared for without darkness there can be no light. You became adept at reading celestial patterns, deciphering their messages, and drawing strength from the cosmic forces that flowed through you. Simultaneously, you embraced your calling as a Twilight domain cleric, further delving into the mysteries of the dusk and dawn. You became a beacon of hope for those lost in the shadows, your divine spells and celestial magic a twinkling light in the darkness that sought to engulf the realm.')
    .setMagicItemsByTier(0, item('Candle of Invocation'))
    .setMagicItemsByTier(1, item('Staff of Healing'))
    .setMagicItemsByTier(2, item('Mithral Armor') + item('Moon Sickle'))
     // 11 15 - 7 8
    .setRecommendedSpellsByTier(1, ['Faerie Fire*', 'Guiding Bolt*', 'Goodberry', 'Healing Word', 'Bless', 'Inflict Wounds', 'Cure Wounds']) // 2 3
    .setRecommendedSpellsByTier(2, ['Aid', 'Lesser Restoration', 'Silence', 'Spiritual Weapon', 'Healing Spirit']) // 3 2
    .setRecommendedSpellsByTier(3, ['Aura of Vitality*', 'Leomund\'s Tiny Hut*', 'Beacon of Hope', 'Mass Healing Word', 'Revivify', 'Dispel Magic']) // 2 2
    .setRecommendedSpellsByTier(4, []) // 0 0
    .setRecommendedSpellsByTier(5, ['Greater Restoration', 'Mass Cure Wounds', 'Maelstrom']) // 0 3
    .setRecommendedSpellsNotes('These core spells only account of for 15 of the 26 druid/cleric spells you can have prepared. You may pick up a few of your favorite spells and add them to the list.')
    .setOtherNotes('This build is thematically amazing. You are a cleric of the night who uses the power of the stars to heal and shield your allies. You carry a MOON Sickle and a CANDLE of Invocation. Its just great.')
    .addAffinityVector(new AffinityVector('TANK', NONE))
    .addAffinityVector(new AffinityVector('MELEE_DPS', NONE))
    .addAffinityVector(new AffinityVector('RANGED_DPS', NONE))
    .addAffinityVector(new AffinityVector('CASTER_DPS', SOME))
    .addAffinityVector(new AffinityVector('SUPPORT', OTP))
    .addAffinityVector(new AffinityVector('POWER', SOME))
    .addAffinityVector(new AffinityVector('UNIQUENESS', NONE))
    .addAffinityVector(new AffinityVector('EXPERT', NONE))
    .addAffinityVector(new AffinityVector('VERSATILITY', NONE))
    .addAffinityVector(new AffinityVector('MULTICLASS', SOME))
    .addAffinityVector(new AffinityVector('NIMBLE', NONE))
    .addAffinityVector(new AffinityVector('STALWART', NONE))
    .addAffinityVector(new AffinityVector('FIELD', SOME))
    .addAffinityVector(new AffinityVector('MAGIC', VERY))
    .addAffinityVector(new AffinityVector('DEFENCE', SOME))
    .addAffinityVector(new AffinityVector('NOVA', SOME))
    .addAffinityVector(new AffinityVector('BUFF', SOME))
    .addAffinityVector(new AffinityVector('DEBUFF', SOME))
    .addAffinityVector(new AffinityVector('HEAL', CRITICAL))
    .addAffinityVector(new AffinityVector('SHIELD', CRITICAL))
    .addAffinityVector(new AffinityVector('SAVE', NONE))
    .addAffinityVector(new AffinityVector('AOE', VERY))
    .addAffinityVector(new AffinityVector('ST', SOME))
    .build()
);

potentialCharacters.push(
    new CharacterBuilder()
    .setBuildName('The Twilight Princess')
    .setMainClass('Cleric')
    .setSubClass('Twilight Domain')
    .setLevels(16)
    .setHasPlaytestMaterial(false)
    .setHasHomebrewMaterial(false)
    .setBuildDraw('The Twilight Princess is a build designed to make the most of the Twilight Domain\'s Channel Divinity: Twilight Sanctuary. This build is a support powerhouse, providing a constant stream of temporary hit points. This specific version of a Twilight Cleric is designed to rely on the Twilight Sanctuary to keep the party healthy (even if it fails to do so), while you focus on casting spells that provide control, debuffs and damage.')
    .setNarritiveDescription('A master of twilight, you have embraced both the light and the darkness, preferring instead to tread the path between the two. You command both the light to heal and empower allies and the darkness to weaken and destroy your enemies. You have also mastered the the powers between light an darkness, using them on the battlefield to protect, manipulate, and control. You are a beacon of hope and a bringer of despair, a healer and a destroyer, a protector and a conqueror. You are the Twilight Cleric.')
    .setMainClassGameplayDescription('As a Cleric, you have access to every spell on the Cleric spell list, and you can change which spells you prepare from this list every long rest. This allows you the unique ability to prepare exactly the tools you need for any encounter. Clerics naturally have access to many of the best healing and support spells in the game as well as several very powerful damaging abilities. The Twilight Domain gives you access to heavy armor, a few unique (and very powerful) spells, and a few unique abilities. The most important of these abilities is the Channel Divinity: Twilight Sanctuary. This is your bread and butter and you will have this up essentially all the time. It will essentially give every ally 20 temporary hit points every round. This, along with your preferred concentration spell (Bless, Circle of Power, Aura of Vitality being your most used) will provide an incredible amount of value to your team every round and once both are up you will still have your action and bonus action to provide further support or toss out some control or damage spells.')
    .setFeats('+2 WIS, +1 WIS/+1 CON, Resilient(CON), and War Caster should probably be your 4 ASIs. This gets you 20 WIS and 18 CON as well as CON proficiency and advantage on CON saves used to maintain concentration.')
    .setRace('Any Race works so long as you use the "Customize Your Origin" rule to get +2 WIS and +1 to CON. Aasimar is always cool.')
    .setAttributes('STR: 8, DEX: 14, CON: 16, INT: 10, WIS: 17, CHA: 8')
    .setBackground('In the realm of Eldoria, where the boundaries between day and night are thin and magical energies flow like a river, you first emerged. Born into a family of skilled healers and devoted to the Twilight Domain, Your destiny was intertwined with the delicate balance between light and darkness. Your early years were marked by a mysterious event during a rare celestial alignment, where you and your family found yourselves in the ethereal realm between dusk and dawn. This event imbued you with a unique connection to the Twilight Domain, granting you the ability to harness both the healing powers of dawn and the shadowy magic of dusk. As you grew older, you embarked on a quest to understand the origins of your powers and master the secrets of the Twilight Domain. Guided by a series of prophetic dreams, you traveled across Eldoria, seeking ancient temples and hidden sanctuaries where the boundaries of light and darkness were blurred. During your travels, you encountered various challenges and adversaries that tested your resolve. You faced malevolent creatures from the Plane of Shadows and delved into long-forgotten libraries seeking ancient texts on twilight magic. Through years of study and communion with the mystical forces, you not only mastered the art of healing but also became adept at manipulating shadows and tapping into the twilight energies that permeate Eldoria. Your abilities transcended those of ordinary clerics who deem the light the only moral source of power. Your embrace of the darkness has made you a powerful ally and terrifying enemy.')
    .setMagicItemsByTier(0, '+3 ' + item('Amulet of the Devout') + ' OR ' + item('Candle of Invocation') + ' OR ' + item('Rod of Absorbtion'))
    .setMagicItemsByTier(1, '+2 ' + item('Amulet of the Devout') + ' OR ' + item('Ring of Spell Storing'))
    .setMagicItemsByTier(2, item('Mithral Armor') + '(Plate) AND ' + '+1 ' + item('Amulet of the Devout') + ' OR ' + item('Sentinal Shield') + ' OR ' + item('Pearl of Power') + ' OR ' + item('Stone of Good Luck'))
    .setRecommendedSpellsByTier(1, ['Faerie Fire*', 'Healing Word', 'Bless', 'Guiding Bolt', 'Inflict Wounds', 'Cure Wounds']) // 5
    .setRecommendedSpellsByTier(2, ['Aid', 'Lesser Restoration', 'Silence', 'Spiritual Weapon']) // 4
    .setRecommendedSpellsByTier(3, ['Aura of Vitality*', 'Leomund\'s Tiny Hut*', 'Beacon of Hope', 'Mass Healing Word', 'Revivify', 'Spirit Guardians']) // 4
    .setRecommendedSpellsByTier(4, ['Aura of Life*', 'Greater Invisibility*', 'Death Ward']) // 1
    .setRecommendedSpellsByTier(5, ['Circle of Power*', 'Greater Restoration', 'Mass Cure Wounds']) // 2
    .setRecommendedSpellsByTier(6, ['Heal', 'Heroes\' Feast']) // 2
    .setRecommendedSpellsByTier(7, ['Fire Storm']) // 1
    .setRecommendedSpellsByTier(8, ['Holy Aura', 'Sunburst']) // 2
    .setRecommendedSpellsNotes('You can prepare 21 spells at level 16 with 20 WIS. The above list consists of all 21. You can change this list every long rest so don\'t worry too much about it, just grab the ones you like best. Be careful not to grab too many concentration spells, you will probably want to be concentrating on Circle of Power, Bless, or Aura of Vitality most of the time. I do recommend swapping out several of the spells on this list for your favorite non-concentration debuff/harmful spells.')
    .setOtherNotes('There are lots of choices for magic items in this build but the decision should be fairly easy if you determine how you would like to play. The level of your Amulet of the Devout is only helpful offensively so the more offensive you plan to play, the higher level you should get. The Rod of Absorbtion is a great choice for your own defenses while the Candle of Invocation is a great choice to help defend your allies. The Ring of Spell Storing is a great choice if you want to be able to cast more spells. Sentinal Shield grants you advantage on initiative, which allows you to use your Twilight Domain feature to give someone else advantage on initiative without having to worry about if it would be better on you instead. The Mithral Armor is really the only mandatory item in this build. The rest is up to you.')
    .addAffinityVector(new AffinityVector('TANK', NONE))
    .addAffinityVector(new AffinityVector('MELEE_DPS', NONE))
    .addAffinityVector(new AffinityVector('RANGED_DPS', NONE))
    .addAffinityVector(new AffinityVector('CASTER_DPS', SOME))
    .addAffinityVector(new AffinityVector('SUPPORT', OTP))
    .addAffinityVector(new AffinityVector('POWER', SOME))
    .addAffinityVector(new AffinityVector('UNIQUENESS', NEGATIVE))
    .addAffinityVector(new AffinityVector('EXPERT', NONE))
    .addAffinityVector(new AffinityVector('VERSATILITY', SOME))
    .addAffinityVector(new AffinityVector('MULTICLASS', NEGATIVE))
    .addAffinityVector(new AffinityVector('NIMBLE', NONE))
    .addAffinityVector(new AffinityVector('STALWART', SOME))
    .addAffinityVector(new AffinityVector('FIELD', SOME))
    .addAffinityVector(new AffinityVector('MAGIC', VERY))
    .addAffinityVector(new AffinityVector('DEFENCE', SOME))
    .addAffinityVector(new AffinityVector('NOVA', SOME))
    .addAffinityVector(new AffinityVector('BUFF', SOME))
    .addAffinityVector(new AffinityVector('DEBUFF', VERY))
    .addAffinityVector(new AffinityVector('HEAL', SOME))
    .addAffinityVector(new AffinityVector('SHIELD', OTP))
    .addAffinityVector(new AffinityVector('SAVE', NONE))
    .addAffinityVector(new AffinityVector('AOE', CRITICAL))
    .addAffinityVector(new AffinityVector('ST', NONE))
    .build()
);

potentialCharacters.push(
    new CharacterBuilder()
    .setBuildName('The Burst of Light')
    .setMainClass('Cleric')
    .setSubClass('Light Domain')
    .setLevels(14)
    .setMultiClass('Fighter')
    .setMultiClassSubClass('N/A')
    .setMultiClassLevels(2)
    .setHasPlaytestMaterial(false)
    .setHasHomebrewMaterial(false)
    .setBuildDraw('This build is a fireball throwing build, pure and simple. Wizards and Sorcerers are known for their fireball throwing abilities, but this build far surpasses them in terms of damage; and it can do so while also having the ability to support the party when needed.')
    .setNarritiveDescription('Light flickers in your eyes, the unstable light reflected from the scene in front of you. The light brings you joy as you reflect on the righteous work you have done today. You have brought The Light to this town, the pure and unadulterated Light of your god. There is no light as pure and as powerful as The Light of your god, and you are the vessel through which it shines. You are The Light in the darkness, the beacon of hope, and the bringer of justice. You are The Light of the world. Only the pure and cleansing Light of fire can cleanse the world of the darkness that plagues it. You laugh as the fire consumes the town, The Light of your god reflected in your eyes.')
    .setMainClassGameplayDescription('Note Cleric is your "main" class but level 1 you should be Fighter so you can get heavy armor and CON save proficiency. This is a fireball throwing build, pure and simple. We go Light Cleric to get our Fireball spell for free as well as access to Cleric\'s incredible spell list, including Spirit Guardians and Spiritual Weapon (both of which you can have active WHILE throwing fireballs) which would not be accessible to your normal fireball throwing class.')
    .setMultiClassGameplayDescription('Fighter levels just for heavy armor, CON save proficiency, fighting style, and action surge. You can take the fighting style of your choice but I recommend Defense for the extra AC. Action surge is great for when you need to throw two fireballs in a single turn.')
    .setMultiClassSubClassGameplayDescription('If you wanna go crazy take two levels of Wizard for the Evocation subclass. This will allow you to throw fireballs at your allies without hurting them. This is a great choice if you are worried about friendly fire. This does not hurt your spell slot progression since you are just upcasting fireball and spirit guardians but if you wanted to cast something other than fireball (why tho?) you won\'t have access to the higher level cleric spells.')
    .setFeats('+2 WIS, and +2 WIS again to cap your Wisdom is pretty mandatory. For your third feat War Caster and Elemental Adept (Fire) are great choices. So good, in fact, that you might even consider going Custom Lineage or Varient Human so we can get both.')
    .setRace('Any Race works so long as you use the "Customize Your Origin" rule to get +2 WIS and +1 to CON. Aasimar, Tiefling, or Fire Genasi are all fun thematic choices.')
    .setAttributes('STR: 8, DEX: 14, CON: 16, INT: 12, WIS: 16, CHA: 8')
    .setBackground('Once a devoted and charismatic cleric of the Light Domain, Seraphina Dawnrider\'s journey began in the peaceful town of Luminara. Raised in the temple of Lathander, the god of dawn and renewal, she dedicated her life to spreading light and hope throughout the realms. Seraphina\'s radiant presence and healing abilities earned her the admiration of the townsfolk, and she was considered a beacon of optimism. However, the balance within Seraphina\'s mind was fragile from the start. Burdened by her own personal struggles, the weight of expectation, and an intense fear of the encroaching darkness, she grappled with an internal conflict that festered over time. She harbored a secret longing for power and a desire to control the forces of light and flame that she believed could cleanse the world of its perceived impurities. One fateful night, during a harrowing mission to purge a nearby village of undead creatures, Seraphina experienced a traumatic event that shattered her sanity. Witnessing the suffering of innocent people and feeling overwhelmed by the darkness that seemed to close in on her, she snapped. In the midst of battle, she tapped into a forbidden source of power that twisted the pure essence of light within her. From that moment on, Seraphina\'s once-golden eyes glowed with an unnatural and eerie flame. Her connection to the Light Domain became distorted, and she now believed that the only way to save the world was to set it ablaze. Consumed by a manic obsession with purifying the realms through fire, she began to interpret her divine visions as instructions to unleash a cleansing inferno. Driven by her newfound insanity, Seraphina left Luminara in ruins, setting fire to the very town that once revered her. She became a wandering flamebringer, leaving scorched landscapes and chaos in her wake. Her actions attracted the attention of those who sought to stop her, including other followers of Lathander who saw her as a perversion of their faith. As Seraphina roams the lands, her unhinged laughter and the haunting glow of her eyes serve as a warning to those who cross her path. The once-devoted cleric has become a force of destruction, convinced that only through the cleansing power of fire can the world be reborn into a new dawn.')
    .setMagicItemsByTier(0, item('Amulet of the Devout'))
    .setMagicItemsByTier(1, item('Ring of Spell Storing'))
    .setMagicItemsByTier(2, item('Winged Boots') + ' AND ' + item('Pearl of Power'))
    .setRecommendedSpellsByTier(1, ['Burning Hands*', 'Faerie Fire*', 'Guiding Bolt', 'Healing Word', 'Inflict Wounds'])
    .setRecommendedSpellsByTier(2, ['Flaming Sphere*', 'Scorching Ray*', 'Spiritual Weapon', 'Warding Bond'])
    .setRecommendedSpellsByTier(3, ['Daylight*', 'Fireball*', 'Revivify', 'Spirit Guardians'])
    .setRecommendedSpellsByTier(4, ['4+ Just upcast Fireball/Spirit Guardians/Spiritual Weapon(if you want damage)/Flaming Sphere(if you want to fit the theme)'])
    .setRecommendedSpellsNotes('These core spells do not account for the total amount of spells you can have prepared so you may pick a few of your favorite spells and add them to the list.')
    .setOtherNotes('')
    .addAffinityVector(new AffinityVector('TANK', NONE))
    .addAffinityVector(new AffinityVector('MELEE_DPS', NONE))
    .addAffinityVector(new AffinityVector('RANGED_DPS', NONE))
    .addAffinityVector(new AffinityVector('CASTER_DPS', OTP))
    .addAffinityVector(new AffinityVector('SUPPORT', SOME))
    .addAffinityVector(new AffinityVector('POWER', SOME))
    .addAffinityVector(new AffinityVector('UNIQUENESS', NONE))
    .addAffinityVector(new AffinityVector('EXPERT', NONE))
    .addAffinityVector(new AffinityVector('VERSATILITY', NONE))
    .addAffinityVector(new AffinityVector('MULTICLASS', NEGATIVE))
    .addAffinityVector(new AffinityVector('NIMBLE', NONE))
    .addAffinityVector(new AffinityVector('STALWART', NONE))
    .addAffinityVector(new AffinityVector('FIELD', SOME))
    .addAffinityVector(new AffinityVector('MAGIC', VERY))
    .addAffinityVector(new AffinityVector('DEFENCE', SOME))
    .addAffinityVector(new AffinityVector('NOVA', VERY))
    .addAffinityVector(new AffinityVector('BUFF', SOME))
    .addAffinityVector(new AffinityVector('DEBUFF', SOME))
    .addAffinityVector(new AffinityVector('HEAL', SOME))
    .addAffinityVector(new AffinityVector('SHIELD', NONE))
    .addAffinityVector(new AffinityVector('SAVE', SOME))
    .addAffinityVector(new AffinityVector('AOE', CRITICAL))
    .addAffinityVector(new AffinityVector('ST', NONE))
    .build()
);

potentialCharacters.push(
    new CharacterBuilder()
    .setBuildName('The Chosen One')
    .setMainClass('Sorcerer')
    .setSubClass('Divine Soul')
    .setLevels(11)
    .setMultiClass('Warlock')
    .setMultiClassSubClass('The Celestial')
    .setMultiClassLevels(5)
    .setHasPlaytestMaterial(false)
    .setHasHomebrewMaterial(false)
    .setBuildDraw('The power of The Chosen One when compared to a more traditional support such as a Cleric or Bard comes from your ability to twin your support spells, doubling their effectiveness, as well as your access to recharging Warlock spell slots, allowing you to cast several more high level spells during the day than a normal support. The cherry on top is Warlock Invocations and Pacts. The big downside is not being able to change your spells known, so you have to be very careful about what you pick.')
    .setNarritiveDescription('In the midst of combat, Cedric Lazuli, would lazily conjure radiant energy, casting celestial spells with an indifferent flick of his hand. Hovering above the battlefield on radiant wings, he\'d rain down divine magic, all the while maintaining a nonchalant demeanor. Despite his apparent laziness, the enemies would be overwhelmed by the raw, god-given power that Cedric wielded, ultimately securing victory in the most laid-back fashion possible.')
    .setMainClassGameplayDescription('We take Sorcerer mostly for Metamagic. Twinning, Quickened, and Subtle spell being your most useful, they give you a lot of versatility and power that a normal support does not have. Divine Soul is clearly the best choice for a support Sorcerer. Access to the Cleric spell list is mandatory and almost all of our spells will come from this list.')
    .setMultiClassGameplayDescription('Like Sorcerer, the reason we take Warlock is not really for subclass abilities but rather for the things that come baked into Warlock. And just like Divine Soul, The Celestial gives you access to support spells that you would not normally have access to.')
    .setMultiClassSubClassGameplayDescription('Take whichever pact you like, I recommend Pact of the Chain. For Eldritch Invocations take Armor of Shadows and Eldritch Mind then one of the following: Mire the Mind, Sign of Ill Omen, Investment of the Chain Master, Lance of Lethargy, or Repelling Blast. ')
    .setFeats('For your three ASIs take +2 CHA, +1 CHA/+1 DEX, and Resilient(CON). One more level in Sorcerer will grant you another ASI with which I would bump your dex to 18 to help your AC and initiative.')
    .setRace('Tasha\'s Custom Lineage: +2 CHA and the Inspiring Leader feat.')
    .setAttributes('STR: 8, DEX: 15, CON: 15, INT: 8, WIS: 8, CHA: 17 (yeah I know, sometimes it just be like that)')
    .setBackground('In the realm of Eldoria, where gods and magic intertwined, there lived a seemingly ordinary individual named Cedric Lazuli. Born into a humble family, Cedric was known for his laid-back demeanor and penchant for avoiding any form of responsibility. Little did he know that his destiny was far grander than the cozy confines of his lazy afternoons. One fateful day, as Cedric lounged beneath a sacred oak tree, a radiant being descended from the heavens. Bathed in divine light, the celestial entity revealed itself as Aeloria, the goddess of light and benevolence. Aeloria spoke of an imminent cataclysm threatening the very fabric of Eldoria, and in a twist of fate, Cedric was chosen to be the harbinger of salvation. Despite his divine calling, Cedric couldn\'t shake off his innate laziness. Aeloria, in her infinite wisdom, decided to imbue him with a fraction of her celestial power, hoping it would spark a sense of urgency in his slothful heart. As the divine energy surged through Cedric, he found himself transformed into a Divine Soul Sorcerer, a vessel of both divine and arcane magic. However, Aeloria\'s intervention didn\'t stop there. Realizing that Cedric might need more motivation, she struck a pact with him, granting him the title of Celestial Warlock. In return for his commitment to saving Eldoria, Cedric gained access to additional celestial powers and the guidance of Aeloria\'s celestial servants. Armed with unparalleled raw god-given power, Cedric embarked on his quest to save the world, reluctantly dragging himself into battles against dark forces threatening to plunge Eldoria into chaos. Despite his casual approach and constant complaints about having to "save the day," Cedric\'s god-given abilities proved to be an unstoppable force. As Cedric lazily waltzed through perilous encounters, his companions marveled at the paradox of a seemingly indifferent hero wielding such extraordinary power. His carefree attitude became a source of both frustration and inspiration, as Cedric managed to triumph over evil with a nonchalant smile on his face. In the end, Cedric Lazuli, the Divine Soul Sorcerer and Celestial Warlock, became a legendary figure in Eldoria. His tale was told across the land, a testament to the fact that even the laziest of souls could rise to the occasion when infused with the raw, god-given power needed to save the world.')
    .setMagicItemsByTier(0, item('Rod of Absorbtion') + ' OR ' + item('Candle of Invocation'))
    .setMagicItemsByTier(1, item('Bracers of Defense') + ' OR ' + item('Ring of Spell Storing'))
    .setMagicItemsByTier(2, item('Broom of Flying') + ' AND ' + item('Pearl of Power'))
                                    // 12 6 - 12 6
    .setRecommendedSpellsByTier(1, ['Cure Wounds - Warlock', 'Guiding Bolt - Warlock', 'Healing Word - Consider for Twinning', 'Shield']) // 2 2
    .setRecommendedSpellsByTier(2, ['Lesser Restoration - Warlock', 'Misty Step - Warlock', 'Aid']) // 1 2
    .setRecommendedSpellsByTier(3, ['Counterspell - Warlock', 'Revivify - Warlock', 'Haste - Consider for Twinning']) // 1 2
    .setRecommendedSpellsByTier(4, ['Greater Invisibility - Consider for Twinning']) // 1
    .setRecommendedSpellsByTier(5, ['Greater Restoration - Consider for Twinning', 'Mass Cure Wounds']) // 2
    .setRecommendedSpellsByTier(6, ['Heal - Consider for Twinning', 'Heroes\' Feast']) // 2
    .setRecommendedSpellsNotes('You can know 12 sorcerer/cleric spells and 6 warlock spells at this level. The above list consists of all 6 warlock spells and 9 of the sorcerer/cleric spells. Most of the recommended spells are staples but while adding your last 3 sorcerer/cleric spells feel free to swap out some of the recommended ones as well. Just remember that neither warlocks nor sorcerers can change their known spells and try to prioritize spells that can be twinned to great effect.')
    .setOtherNotes('Consider instead of taking warlock levels taking 4 more levels of sorc and taking your first level as Order cleric. This is potentially a better build but will require several changes. I didn\'t recommend the sorcerer/cleric version because it felt too similar to The Siren but if that sounds interesting feel free to check out The Siren or let me know and I can assist with the changes to this build.')
    .addAffinityVector(new AffinityVector('TANK', NONE))
    .addAffinityVector(new AffinityVector('MELEE_DPS', NONE))
    .addAffinityVector(new AffinityVector('RANGED_DPS', NONE))
    .addAffinityVector(new AffinityVector('CASTER_DPS', VERY))
    .addAffinityVector(new AffinityVector('SUPPORT', CRITICAL))
    .addAffinityVector(new AffinityVector('POWER', SOME))
    .addAffinityVector(new AffinityVector('UNIQUENESS', SOME))
    .addAffinityVector(new AffinityVector('EXPERT', NONE))
    .addAffinityVector(new AffinityVector('VERSATILITY', NEGATIVE))
    .addAffinityVector(new AffinityVector('MULTICLASS', SOME))
    .addAffinityVector(new AffinityVector('NIMBLE', SOME))
    .addAffinityVector(new AffinityVector('STALWART', NONE))
    .addAffinityVector(new AffinityVector('FIELD', SOME))
    .addAffinityVector(new AffinityVector('MAGIC', VERY))
    .addAffinityVector(new AffinityVector('DEFENCE', NEGATIVE))
    .addAffinityVector(new AffinityVector('NOVA', VERY))
    .addAffinityVector(new AffinityVector('BUFF', CRITICAL))
    .addAffinityVector(new AffinityVector('DEBUFF', VERY))
    .addAffinityVector(new AffinityVector('HEAL', CRITICAL))
    .addAffinityVector(new AffinityVector('SHIELD', NONE))
    .addAffinityVector(new AffinityVector('SAVE', NONE))
    .addAffinityVector(new AffinityVector('AOE', SOME))
    .addAffinityVector(new AffinityVector('ST', VERY))
    .build()
);

// potentialCharacters.push(
//     new CharacterBuilder()
//     .setBuildName('The Crusader of the Light')
//     .setMainClass('Bard')
//     .setSubClass('College of Valor')
//     .setLevels(10)
//     .setMultiClass('Paladin')
//     .setMultiClassSubClass('Oath of Devotion')
//     .setMultiClassLevels(6)
//     .setHasPlaytestMaterial(true)
//     .setHasHomebrewMaterial(false)
//     .setBuildDraw('')
//     .setNarritiveDescription('You have an Oath of Devotion and went to the College of Valor. You are a goodie two shoes. There is not much more to say.')
//     .setMainClassGameplayDescription('')
//     .setMultiClassGameplayDescription('')
//     .setMultiClassSubClassGameplayDescription('')
//     .setFeats('')
//     .setRace('')
//     .setAttributes('')
//     .setBackground('')
//     .setMagicItemsByTier(0, 'Ask your DM if you can have BOTH these (and maybe even use both of their bonus actions in a single turn) ' + item('Dancing Sword') + ' and ' + item('Animated Shield') + ' otherwise just PYF Very Rare weapon.')
//     .setMagicItemsByTier(1, item(''))
//     .setMagicItemsByTier(2, item(''))
//     .setRecommendedSpellsByTier(1, [])
//     .setRecommendedSpellsByTier(2, [])
//     .setRecommendedSpellsByTier(3, [])
//     .setRecommendedSpellsByTier(4, [])
//     .setRecommendedSpellsNotes('')
//     .setOtherNotes('We already have two paladins so I\'m not sure if we need another one. Regardless, take Paladin as your first level for heavy armor proficiency.')
//     .addAffinityVector(new AffinityVector('TANK', NONE))
//     .addAffinityVector(new AffinityVector('MELEE_DPS', VERY))
//     .addAffinityVector(new AffinityVector('RANGED_DPS', NONE))
//     .addAffinityVector(new AffinityVector('CASTER_DPS', NONE))
//     .addAffinityVector(new AffinityVector('SUPPORT', CRITICAL))
//     .addAffinityVector(new AffinityVector('POWER', VERY))
//     .addAffinityVector(new AffinityVector('UNIQUENESS', NEGATIVE))
//     .addAffinityVector(new AffinityVector('EXPERT', NONE))
//     .addAffinityVector(new AffinityVector('VERSATILITY', SOME))
//     .addAffinityVector(new AffinityVector('MULTICLASS', VERY))
//     .addAffinityVector(new AffinityVector('NIMBLE', NONE))
//     .addAffinityVector(new AffinityVector('STALWART', SOME))
//     .addAffinityVector(new AffinityVector('FIELD', SOME))
//     .addAffinityVector(new AffinityVector('MAGIC', SOME))
//     .addAffinityVector(new AffinityVector('DEFENCE', VERY))
//     .addAffinityVector(new AffinityVector('NOVA', SOME))
//     .addAffinityVector(new AffinityVector('BUFF', CRITICAL))
//     .addAffinityVector(new AffinityVector('DEBUFF', SOME))
//     .addAffinityVector(new AffinityVector('HEAL', SOME))
//     .addAffinityVector(new AffinityVector('SHIELD', NONE))
//     .addAffinityVector(new AffinityVector('SAVE', CRITICAL))
//     .addAffinityVector(new AffinityVector('AOE', CRITICAL))
//     .addAffinityVector(new AffinityVector('ST', NONE))
//     .build()
// );
/*
potentialCharacters.push(
    new CharacterBuilder()
    .setBuildName('')
    .setMainClass('')
    .setSubClass('')
    .setLevels(10)
    .setMultiClass('')
    .setMultiClassSubClass('')
    .setMultiClassLevels(6)
    .setHasPlaytestMaterial(false)
    .setHasHomebrewMaterial(false)
    .setBuildDraw('')
    .setNarritiveDescription('')
    .setMainClassGameplayDescription('')
    .setMultiClassGameplayDescription('')
    .setMultiClassSubClassGameplayDescription('')
    .setFeats('')
    .setRace('')
    .setAttributes('')
    .setBackground('')
    .setMagicItemsByTier(0, item(''))
    .setMagicItemsByTier(1, item(''))
    .setMagicItemsByTier(2, item(''))
    .setRecommendedSpellsByTier(1, [])
    .setRecommendedSpellsByTier(2, [])
    .setRecommendedSpellsByTier(3, [])
    .setRecommendedSpellsByTier(4, [])
    .setRecommendedSpellsByTier(5, [])
    .setRecommendedSpellsNotes('')
    .setOtherNotes('')
    .addAffinityVector(new AffinityVector('TANK', NONE))
    .addAffinityVector(new AffinityVector('MELEE_DPS', NONE))
    .addAffinityVector(new AffinityVector('RANGED_DPS', NONE))
    .addAffinityVector(new AffinityVector('CASTER_DPS', NONE))
    .addAffinityVector(new AffinityVector('SUPPORT', NONE))
    .addAffinityVector(new AffinityVector('POWER', NONE))
    .addAffinityVector(new AffinityVector('UNIQUENESS', NONE))
    .addAffinityVector(new AffinityVector('EXPERT', NONE))
    .addAffinityVector(new AffinityVector('VERSATILITY', NONE))
    .addAffinityVector(new AffinityVector('MULTICLASS', NONE))
    .addAffinityVector(new AffinityVector('NIMBLE', NONE))
    .addAffinityVector(new AffinityVector('STALWART', NONE))
    .addAffinityVector(new AffinityVector('FIELD', NONE))
    .addAffinityVector(new AffinityVector('MAGIC', NONE))
    .addAffinityVector(new AffinityVector('DEFENCE', NONE))
    .addAffinityVector(new AffinityVector('NOVA', NONE))
    .addAffinityVector(new AffinityVector('BUFF', NONE))
    .addAffinityVector(new AffinityVector('DEBUFF', NONE))
    .addAffinityVector(new AffinityVector('HEAL', NONE))
    .addAffinityVector(new AffinityVector('SHIELD', NONE))
    .addAffinityVector(new AffinityVector('SAVE', NONE))
    .addAffinityVector(new AffinityVector('AOE', NONE))
    .addAffinityVector(new AffinityVector('ST', NONE))
    .build()
);
*/

potentialCharacters.push(
    new CharacterBuilder()
    .setBuildName('The Psyknife')
    .setMainClass('Rogue')
    .setSubClass('Soulknife')
    .setLevels(9)
    .setMultiClass('Fighter')
    .setMultiClassSubClass('Psi Warrior')
    .setMultiClassLevels(7)
    .setHasPlaytestMaterial(false)
    .setHasHomebrewMaterial(false)
    .setBuildDraw('')
    .setNarritiveDescription('')
    .setMainClassGameplayDescription('')
    .setMultiClassGameplayDescription('')
    .setMultiClassSubClassGameplayDescription('')
    .setFeats('Telekinetic, Telepathic, +2 DEX')
    .setRace('Gem Dragonborn')
    .setAttributes('')
    .setBackground('')
    .setMagicItemsByTier(0, 'Beg your DM or Artificer for a returning dagger. Otherwise you will be feeling bad throwing non-magical daggers all the time.')
    .setMagicItemsByTier(1, item(''))
    .setMagicItemsByTier(2, item(''))
    .addAffinityVector(new AffinityVector('TANK', NONE))
    .addAffinityVector(new AffinityVector('MELEE_DPS', VERY))
    .addAffinityVector(new AffinityVector('RANGED_DPS', CRITICAL))
    .addAffinityVector(new AffinityVector('CASTER_DPS', NONE))
    .addAffinityVector(new AffinityVector('SUPPORT', NONE))
    .addAffinityVector(new AffinityVector('POWER', VERY))
    .addAffinityVector(new AffinityVector('UNIQUENESS', NONE))
    .addAffinityVector(new AffinityVector('EXPERT', SOME))
    .addAffinityVector(new AffinityVector('VERSATILITY', NONE))
    .addAffinityVector(new AffinityVector('MULTICLASS', VERY))
    .addAffinityVector(new AffinityVector('NIMBLE', SOME))
    .addAffinityVector(new AffinityVector('STALWART', NONE))
    .addAffinityVector(new AffinityVector('FIELD', SOME))
    .addAffinityVector(new AffinityVector('MAGIC', NONE))
    .addAffinityVector(new AffinityVector('DEFENCE', NEGATIVE))
    .addAffinityVector(new AffinityVector('NOVA', NEGATIVE))
    .addAffinityVector(new AffinityVector('BUFF', NONE))
    .addAffinityVector(new AffinityVector('DEBUFF', NONE))
    .addAffinityVector(new AffinityVector('HEAL', NONE))
    .addAffinityVector(new AffinityVector('SHIELD', NONE))
    .addAffinityVector(new AffinityVector('SAVE', NONE))
    .addAffinityVector(new AffinityVector('AOE', NONE))
    .addAffinityVector(new AffinityVector('ST', CRITICAL))
    .build()
);

potentialCharacters.push(
    new CharacterBuilder()
    .setBuildName('The Arcane Archer')
    .setMainClass('Fighter')
    .setSubClass('Arcane Archer')
    .setLevels(11)
    .setMultiClass('Sorcerer')
    .setMultiClassSubClass('Wild Magic')
    .setMultiClassLevels(5)
    .setHasPlaytestMaterial(false)
    .setHasHomebrewMaterial(false)
    .setBuildDraw('')
    .setNarritiveDescription('')
    .setMainClassGameplayDescription('')
    .setMultiClassGameplayDescription('')
    .setMultiClassSubClassGameplayDescription('')
    .setFeats('Sharpshooter, Magic Initiate to snag Faerie Fire, and +2 DEX')
    .setRace('Eladrin')
    .setAttributes('')
    .setBackground('')
    .setMagicItemsByTier(0, item(''))
    .setMagicItemsByTier(1, item(''))
    .setMagicItemsByTier(2, item(''))
    .setRecommendedSpellsByTier(1, [])
    .setRecommendedSpellsByTier(2, [])
    .setRecommendedSpellsByTier(3, [])
    .setRecommendedSpellsByTier(4, [])
    .setRecommendedSpellsNotes('')
    .setOtherNotes('')
    .addAffinityVector(new AffinityVector('TANK', NONE))
    .addAffinityVector(new AffinityVector('MELEE_DPS', NONE))
    .addAffinityVector(new AffinityVector('RANGED_DPS', CRITICAL))
    .addAffinityVector(new AffinityVector('CASTER_DPS', VERY))
    .addAffinityVector(new AffinityVector('SUPPORT', NONE))
    .addAffinityVector(new AffinityVector('POWER', SOME))
    .addAffinityVector(new AffinityVector('UNIQUENESS', SOME))
    .addAffinityVector(new AffinityVector('EXPERT', NONE))
    .addAffinityVector(new AffinityVector('VERSATILITY', NONE))
    .addAffinityVector(new AffinityVector('MULTICLASS', VERY))
    .addAffinityVector(new AffinityVector('NIMBLE', SOME))
    .addAffinityVector(new AffinityVector('STALWART', NONE))
    .addAffinityVector(new AffinityVector('FIELD', SOME))
    .addAffinityVector(new AffinityVector('MAGIC', NONE))
    .addAffinityVector(new AffinityVector('DEFENCE', NEGATIVE))
    .addAffinityVector(new AffinityVector('NOVA', NEGATIVE))
    .addAffinityVector(new AffinityVector('BUFF', NONE))
    .addAffinityVector(new AffinityVector('DEBUFF', NONE))
    .addAffinityVector(new AffinityVector('HEAL', NONE))
    .addAffinityVector(new AffinityVector('SHIELD', NONE))
    .addAffinityVector(new AffinityVector('SAVE', NONE))
    .addAffinityVector(new AffinityVector('AOE', SOME))
    .addAffinityVector(new AffinityVector('ST', VERY))
    .build()
);

potentialCharacters.push(
    new CharacterBuilder()
    .setBuildName('The Lich King')
    .setMainClass('Warlock')
    .setSubClass('The Undying')
    .setLevels(11)
    .setMultiClass('Paladin')
    .setMultiClassSubClass('Oath of Vengeance')
    .setMultiClassLevels(5)
    .setHasPlaytestMaterial(true)
    .setHasHomebrewMaterial(false)
    .setBuildDraw('')
    .setNarritiveDescription('')
    .setMainClassGameplayDescription('')
    .setMultiClassGameplayDescription('')
    .setMultiClassSubClassGameplayDescription('')
    .setFeats('Mounted Combatant, Elven Accuracy, +2 CHA')
    .setRace('Elf')
    .setAttributes('')
    .setBackground('')
    .setMagicItemsByTier(0, item('Dragon\'s Wrath Weapon'))
    .setMagicItemsByTier(1, item('Butcher\'s Bib'))
    .setMagicItemsByTier(2, item('Saddle of the Cavalier') + ' AND ' + item('Gauntlets of Ogre Power'))
    .setRecommendedSpellsByTier(1, [])
    .setRecommendedSpellsByTier(2, [])
    .setRecommendedSpellsByTier(3, [])
    .setRecommendedSpellsByTier(4, [])
    .setRecommendedSpellsNotes('')
    .setOtherNotes('')
    .addAffinityVector(new AffinityVector('TANK', NONE))
    .addAffinityVector(new AffinityVector('MELEE_DPS', CRITICAL))
    .addAffinityVector(new AffinityVector('RANGED_DPS', NONE))
    .addAffinityVector(new AffinityVector('CASTER_DPS', VERY))
    .addAffinityVector(new AffinityVector('SUPPORT', NONE))
    .addAffinityVector(new AffinityVector('POWER', SOME))
    .addAffinityVector(new AffinityVector('UNIQUENESS', SOME))
    .addAffinityVector(new AffinityVector('EXPERT', NONE))
    .addAffinityVector(new AffinityVector('VERSATILITY', NEGATIVE))
    .addAffinityVector(new AffinityVector('MULTICLASS', SOME))
    .addAffinityVector(new AffinityVector('NIMBLE', NONE))
    .addAffinityVector(new AffinityVector('STALWART', SOME))
    .addAffinityVector(new AffinityVector('FIELD', SOME))
    .addAffinityVector(new AffinityVector('MAGIC', NONE))
    .addAffinityVector(new AffinityVector('DEFENCE', NEGATIVE))
    .addAffinityVector(new AffinityVector('NOVA', VERY))
    .addAffinityVector(new AffinityVector('BUFF', NONE))
    .addAffinityVector(new AffinityVector('DEBUFF', NONE))
    .addAffinityVector(new AffinityVector('HEAL', NONE))
    .addAffinityVector(new AffinityVector('SHIELD', NONE))
    .addAffinityVector(new AffinityVector('SAVE', NONE))
    .addAffinityVector(new AffinityVector('AOE', NONE))
    .addAffinityVector(new AffinityVector('ST', CRITICAL))
    .build()
);