import { CharacterBuilder } from '../Character.js';
import { AffinityVector } from '../AffinityVector.js';
export let potentialCharacters = []

let OTP = 20;
let CRITICAL = 15;
let VERY = 10;
let SOME = 5;
let NONE = 0;
let NEGATIVE = -5;
let VERY_NEGATIVE = -10;


potentialCharacters.push(
    new CharacterBuilder()
    .setBuildName('The Dancer')
    .setMainClass('Bard')
    .setSubClass('College of Dance')
    .setLevels(11)
    .setMultiClass('Monk')
    .setMultiClassSubClass('Warrior of Mercy')
    .setMultiClassLevels(5)
    .setHasPlaytestMaterial(true)
    .setHasHomebrewMaterial(false)
    .setNarritiveDescription('You are as nimble as they come. In combat you are seen weaving through the battlefield with unparalleled speed. One moment healing your wounded backline and the next unleashing a flurry of blows upon the backline of the enemy. As you move your voice rises in an inspiring chant, encouraging your comrades and boosting their morale. Your bardic magic filling the air. Your allies are invincible with you by their side and your enemies fall at your hands. All this, and you don\'t even wield weapons or armor, it just wouldn\'t be fair.')
    .setMainClassGameplayDescription('Your core gameplay loop revolves around Agile Strikes and Font of Inspiration. Font of Inspiration allows you to use Bardic Inspiration every turn without running out of uses while Agile Strikes allows these Bardic Inspiration uses to also grant you a free unarmed attack. Using your bardic inspiration as a bonus action every turn will allow you to constantly hand out the die while also dishing out punches to the enemies, all without using your action which can be saved for a powerful spell or more punches.')
    .setMultiClassGameplayDescription('Your monk levels enhance your free unarmed attacks as well as your movement: making you even more slippery and able to dash around the battle field to wherever you\'re needed.')
    .setMultiClassSubClassGameplayDescription('Your monk subclass allows you to heal with just a touch, giving you another resource for healing if you are low on spell slots')
    .setOtherNotes('Unarmored Defense, Inspiring Movement, Tandem Footwork, and Leading Evasion allow you and your party to move quickly; making them less likely to take damage, be higher on the turn order, and to stay out of danger.')
    .addAffinityVector(new AffinityVector('TANK', NONE))
    .addAffinityVector(new AffinityVector('MELEE_DPS', VERY))
    .addAffinityVector(new AffinityVector('RANGED_DPS', NONE))
    .addAffinityVector(new AffinityVector('CASTER_DPS', NONE))
    .addAffinityVector(new AffinityVector('SUPPORT', CRITICAL))
    .addAffinityVector(new AffinityVector('POWER', SOME))
    .addAffinityVector(new AffinityVector('UNIQUENESS', SOME))
    .addAffinityVector(new AffinityVector('EXPERT', SOME))
    .addAffinityVector(new AffinityVector('VERSATILITY', SOME))
    .addAffinityVector(new AffinityVector('MULTICLASS', VERY))
    .addAffinityVector(new AffinityVector('NIMBLE', SOME))
    .addAffinityVector(new AffinityVector('STALWART', NONE))
    .addAffinityVector(new AffinityVector('FIELD', SOME))
    .addAffinityVector(new AffinityVector('MAGIC', SOME))
    .addAffinityVector(new AffinityVector('DEFENCE', SOME))
    .addAffinityVector(new AffinityVector('NOVA', NEGATIVE))
    .addAffinityVector(new AffinityVector('BUFF', SOME))
    .addAffinityVector(new AffinityVector('DEBUFF', NONE))
    .addAffinityVector(new AffinityVector('HEAL', NONE))
    .addAffinityVector(new AffinityVector('SHIELD', NONE))
    .addAffinityVector(new AffinityVector('SAVE', VERY))
    .build()
);

potentialCharacters.push(
    new CharacterBuilder()
    .setBuildName('The Siren')
    .setMainClass('Bard')
    .setSubClass('College of Lore')
    .setLevels(16)
    .setHasPlaytestMaterial(false)
    .setHasHomebrewMaterial(false)
    .setNarritiveDescription('Your words drip with power, your every syllable unnerving enemies and empowering friends.  Chanting your arcane verse you unleash the culmination of your thorough magical studies. Through a lifelong commitment to knowledge you have amassed the ability to cast almost any spell and you wield this knowledge as a weapon and a shield, your knowledge of the arcane granting you a diverse arsenal of spells to bring to bear in any combat.')
    .setMainClassGameplayDescription('Through Magical Secrets and Additional Magical Secrets, you have access to a wide variety of spells, allowing you to adapt to any situation. Your Bardic Inspiration and Cutting Words allow you to control the battlefield and the flow of combat. Your spellcasting is your primary focus, and you have amongst the largest amount of prepared spells as well as access to all spells in the game.')
    .setOtherNotes('You have lots of additional utility from Song of Rest, Countercharm, and Peerless Skill. You can also use your Bardic Inspiration to help your allies with their saving throws.')
    .addAffinityVector(new AffinityVector('TANK', NONE))
    .addAffinityVector(new AffinityVector('MELEE_DPS', NONE))
    .addAffinityVector(new AffinityVector('RANGED_DPS', NONE))
    .addAffinityVector(new AffinityVector('CASTER_DPS', CRITICAL))
    .addAffinityVector(new AffinityVector('SUPPORT', CRITICAL))
    .addAffinityVector(new AffinityVector('POWER', VERY))
    .addAffinityVector(new AffinityVector('UNIQUENESS', NONE))
    .addAffinityVector(new AffinityVector('EXPERT', SOME))
    .addAffinityVector(new AffinityVector('VERSATILITY', VERY))
    .addAffinityVector(new AffinityVector('MULTICLASS', VERY_NEGATIVE))
    .addAffinityVector(new AffinityVector('NIMBLE', NONE))
    .addAffinityVector(new AffinityVector('STALWART', NONE))
    .addAffinityVector(new AffinityVector('FIELD', NONE))
    .addAffinityVector(new AffinityVector('MAGIC', VERY))
    .addAffinityVector(new AffinityVector('DEFENCE', NEGATIVE))
    .addAffinityVector(new AffinityVector('NOVA', SOME))
    .addAffinityVector(new AffinityVector('BUFF', NONE))
    .addAffinityVector(new AffinityVector('DEBUFF', SOME))
    .addAffinityVector(new AffinityVector('HEAL', NONE))
    .addAffinityVector(new AffinityVector('SHIELD', NONE))
    .addAffinityVector(new AffinityVector('SAVE', SOME))
    .build()
);

potentialCharacters.push(
    new CharacterBuilder()
    .setBuildName('The Psyknife')
    .setMainClass('Rogue')
    .setSubClass('Soulknife')
    .setLevels(9)
    .setMultiClass('Fighter')
    .setMultiClassSubClass('Psi Warrior')
    .setMultiClassLevels(7)
    .setHasPlaytestMaterial(false)
    .setHasHomebrewMaterial(false)
    .setNarritiveDescription('')
    .setMainClassGameplayDescription('')
    .setOtherNotes('')
    .addAffinityVector(new AffinityVector('TANK', NONE))
    .addAffinityVector(new AffinityVector('MELEE_DPS', VERY))
    .addAffinityVector(new AffinityVector('RANGED_DPS', CRITICAL))
    .addAffinityVector(new AffinityVector('CASTER_DPS', NONE))
    .addAffinityVector(new AffinityVector('SUPPORT', NONE))
    .addAffinityVector(new AffinityVector('POWER', VERY))
    .addAffinityVector(new AffinityVector('UNIQUENESS', NONE))
    .addAffinityVector(new AffinityVector('EXPERT', SOME))
    .addAffinityVector(new AffinityVector('VERSATILITY', NONE))
    .addAffinityVector(new AffinityVector('MULTICLASS', VERY))
    .addAffinityVector(new AffinityVector('NIMBLE', SOME))
    .addAffinityVector(new AffinityVector('STALWART', NONE))
    .addAffinityVector(new AffinityVector('FIELD', SOME))
    .addAffinityVector(new AffinityVector('MAGIC', NONE))
    .addAffinityVector(new AffinityVector('DEFENCE', NEGATIVE))
    .addAffinityVector(new AffinityVector('NOVA', NEGATIVE))
    .addAffinityVector(new AffinityVector('BUFF', NONE))
    .addAffinityVector(new AffinityVector('DEBUFF', NONE))
    .addAffinityVector(new AffinityVector('HEAL', NONE))
    .addAffinityVector(new AffinityVector('SHIELD', NONE))
    .addAffinityVector(new AffinityVector('SAVE', NONE))
    .build()
);

potentialCharacters.push(
    new CharacterBuilder()
    .setBuildName('Crusader of the Light')
    .setMainClass('Priest')
    .setSubClass('')
    .setLevels(10)
    .setMultiClass('Paladin')
    .setMultiClassSubClass('')
    .setMultiClassLevels(6)
    .setHasPlaytestMaterial(false)
    .setHasHomebrewMaterial(false)
    .setNarritiveDescription('')
    .setMainClassGameplayDescription('')
    .setOtherNotes('')
    .addAffinityVector(new AffinityVector('TANK', SOME))
    .addAffinityVector(new AffinityVector('MELEE_DPS', SOME))
    .addAffinityVector(new AffinityVector('RANGED_DPS', NONE))
    .addAffinityVector(new AffinityVector('CASTER_DPS', VERY))
    .addAffinityVector(new AffinityVector('SUPPORT', CRITICAL))
    .addAffinityVector(new AffinityVector('POWER', VERY))
    .addAffinityVector(new AffinityVector('UNIQUENESS', NEGATIVE))
    .addAffinityVector(new AffinityVector('EXPERT', NONE))
    .addAffinityVector(new AffinityVector('VERSATILITY', SOME))
    .addAffinityVector(new AffinityVector('MULTICLASS', VERY))
    .addAffinityVector(new AffinityVector('NIMBLE', NONE))
    .addAffinityVector(new AffinityVector('STALWART', SOME))
    .addAffinityVector(new AffinityVector('FIELD', SOME))
    .addAffinityVector(new AffinityVector('MAGIC', SOME))
    .addAffinityVector(new AffinityVector('DEFENCE', VERY))
    .addAffinityVector(new AffinityVector('NOVA', SOME))
    .addAffinityVector(new AffinityVector('BUFF', SOME))
    .addAffinityVector(new AffinityVector('DEBUFF', NONE))
    .addAffinityVector(new AffinityVector('HEAL', SOME))
    .addAffinityVector(new AffinityVector('SHIELD', NONE))
    .addAffinityVector(new AffinityVector('SAVE', VERY))
    .build()
);

potentialCharacters.push(
    new CharacterBuilder()
    .setBuildName('Some Druid')
    .setMainClass('Druid')
    .setSubClass('')
    .setLevels(16)
    .setHasPlaytestMaterial(false)
    .setHasHomebrewMaterial(false)
    .setNarritiveDescription('')
    .setMainClassGameplayDescription('')
    .setOtherNotes('')
    .addAffinityVector(new AffinityVector('TANK', NONE))
    .addAffinityVector(new AffinityVector('MELEE_DPS', NONE))
    .addAffinityVector(new AffinityVector('RANGED_DPS', NONE))
    .addAffinityVector(new AffinityVector('CASTER_DPS', SOME))
    .addAffinityVector(new AffinityVector('SUPPORT', OTP))
    .addAffinityVector(new AffinityVector('POWER', NONE))
    .addAffinityVector(new AffinityVector('UNIQUENESS', NONE))
    .addAffinityVector(new AffinityVector('EXPERT', NONE))
    .addAffinityVector(new AffinityVector('VERSATILITY', VERY))
    .addAffinityVector(new AffinityVector('MULTICLASS', VERY_NEGATIVE))
    .addAffinityVector(new AffinityVector('NIMBLE', NONE))
    .addAffinityVector(new AffinityVector('STALWART', NONE))
    .addAffinityVector(new AffinityVector('FIELD', SOME))
    .addAffinityVector(new AffinityVector('MAGIC', VERY))
    .addAffinityVector(new AffinityVector('DEFENCE', SOME))
    .addAffinityVector(new AffinityVector('NOVA', NONE))
    .addAffinityVector(new AffinityVector('BUFF', NONE))
    .addAffinityVector(new AffinityVector('DEBUFF', VERY))
    .addAffinityVector(new AffinityVector('HEAL', VERY))
    .addAffinityVector(new AffinityVector('SHIELD', NONE))
    .addAffinityVector(new AffinityVector('SAVE', NONE))
    .build()
);

potentialCharacters.push(
    new CharacterBuilder()
    .setBuildName('Some Cleric')
    .setMainClass('Cleric')
    .setSubClass('')
    .setLevels(16)
    .setHasPlaytestMaterial(false)
    .setHasHomebrewMaterial(false)
    .setNarritiveDescription('')
    .setMainClassGameplayDescription('')
    .setOtherNotes('')
    .addAffinityVector(new AffinityVector('TANK', NONE))
    .addAffinityVector(new AffinityVector('MELEE_DPS', NONE))
    .addAffinityVector(new AffinityVector('RANGED_DPS', NONE))
    .addAffinityVector(new AffinityVector('CASTER_DPS', VERY))
    .addAffinityVector(new AffinityVector('SUPPORT', OTP))
    .addAffinityVector(new AffinityVector('POWER', VERY))
    .addAffinityVector(new AffinityVector('UNIQUENESS', NONE))
    .addAffinityVector(new AffinityVector('EXPERT', NONE))
    .addAffinityVector(new AffinityVector('VERSATILITY', SOME))
    .addAffinityVector(new AffinityVector('MULTICLASS', VERY_NEGATIVE))
    .addAffinityVector(new AffinityVector('NIMBLE', NONE))
    .addAffinityVector(new AffinityVector('STALWART', SOME))
    .addAffinityVector(new AffinityVector('FIELD', SOME))
    .addAffinityVector(new AffinityVector('MAGIC', VERY))
    .addAffinityVector(new AffinityVector('DEFENCE', SOME))
    .addAffinityVector(new AffinityVector('NOVA', SOME))
    .addAffinityVector(new AffinityVector('BUFF', SOME))
    .addAffinityVector(new AffinityVector('DEBUFF', NONE))
    .addAffinityVector(new AffinityVector('HEAL', VERY))
    .addAffinityVector(new AffinityVector('SHIELD', VERY))
    .addAffinityVector(new AffinityVector('SAVE', NONE))
    .build()
);

potentialCharacters.push(
    new CharacterBuilder()
    .setBuildName('Arcane Archer')
    .setMainClass('Fighter')
    .setSubClass('Arcane Archer')
    .setLevels(11)
    .setMultiClass('Sorcerer')
    .setMultiClassSubClass('Wild Magic')
    .setMultiClassLevels(5)
    .setHasPlaytestMaterial(false)
    .setHasHomebrewMaterial(false)
    .setNarritiveDescription('')
    .setMainClassGameplayDescription('')
    .setOtherNotes('')
    .addAffinityVector(new AffinityVector('TANK', NONE))
    .addAffinityVector(new AffinityVector('MELEE_DPS', NONE))
    .addAffinityVector(new AffinityVector('RANGED_DPS', CRITICAL))
    .addAffinityVector(new AffinityVector('CASTER_DPS', VERY))
    .addAffinityVector(new AffinityVector('SUPPORT', NONE))
    .addAffinityVector(new AffinityVector('POWER', SOME))
    .addAffinityVector(new AffinityVector('UNIQUENESS', SOME))
    .addAffinityVector(new AffinityVector('EXPERT', NONE))
    .addAffinityVector(new AffinityVector('VERSATILITY', NONE))
    .addAffinityVector(new AffinityVector('MULTICLASS', VERY))
    .addAffinityVector(new AffinityVector('NIMBLE', SOME))
    .addAffinityVector(new AffinityVector('STALWART', NONE))
    .addAffinityVector(new AffinityVector('FIELD', SOME))
    .addAffinityVector(new AffinityVector('MAGIC', NONE))
    .addAffinityVector(new AffinityVector('DEFENCE', NEGATIVE))
    .addAffinityVector(new AffinityVector('NOVA', NEGATIVE))
    .addAffinityVector(new AffinityVector('BUFF', NONE))
    .addAffinityVector(new AffinityVector('DEBUFF', NONE))
    .addAffinityVector(new AffinityVector('HEAL', NONE))
    .addAffinityVector(new AffinityVector('SHIELD', NONE))
    .addAffinityVector(new AffinityVector('SAVE', NONE))
    .build()
);

potentialCharacters.push(
    new CharacterBuilder()
    .setBuildName('The Lich King')
    .setMainClass('Warlock')
    .setSubClass('The Undying')
    .setLevels(11)
    .setMultiClass('Paladin')
    .setMultiClassSubClass('Oath of Vengeance')
    .setMultiClassLevels(5)
    .setHasPlaytestMaterial(true)
    .setHasHomebrewMaterial(false)
    .setNarritiveDescription('')
    .setMainClassGameplayDescription('')
    .setOtherNotes('')
    .addAffinityVector(new AffinityVector('TANK', NONE))
    .addAffinityVector(new AffinityVector('MELEE_DPS', CRITICAL))
    .addAffinityVector(new AffinityVector('RANGED_DPS', NONE))
    .addAffinityVector(new AffinityVector('CASTER_DPS', VERY))
    .addAffinityVector(new AffinityVector('SUPPORT', NONE))
    .addAffinityVector(new AffinityVector('POWER', SOME))
    .addAffinityVector(new AffinityVector('UNIQUENESS', SOME))
    .addAffinityVector(new AffinityVector('EXPERT', NONE))
    .addAffinityVector(new AffinityVector('VERSATILITY', NEGATIVE))
    .addAffinityVector(new AffinityVector('MULTICLASS', SOME))
    .addAffinityVector(new AffinityVector('NIMBLE', NONE))
    .addAffinityVector(new AffinityVector('STALWART', SOME))
    .addAffinityVector(new AffinityVector('FIELD', SOME))
    .addAffinityVector(new AffinityVector('MAGIC', NONE))
    .addAffinityVector(new AffinityVector('DEFENCE', NEGATIVE))
    .addAffinityVector(new AffinityVector('NOVA', VERY))
    .addAffinityVector(new AffinityVector('BUFF', NONE))
    .addAffinityVector(new AffinityVector('DEBUFF', NONE))
    .addAffinityVector(new AffinityVector('HEAL', NONE))
    .addAffinityVector(new AffinityVector('SHIELD', NONE))
    .addAffinityVector(new AffinityVector('SAVE', NONE))
    .build()
);

potentialCharacters.push(
    new CharacterBuilder()
    .setBuildName('')
    .setMainClass('')
    .setSubClass('')
    .setLevels(10)
    .setMultiClass('')
    .setMultiClassSubClass('')
    .setMultiClassLevels(6)
    .setHasPlaytestMaterial(false)
    .setHasHomebrewMaterial(false)
    .setNarritiveDescription('')
    .setMainClassGameplayDescription('')
    .setOtherNotes('')
    .addAffinityVector(new AffinityVector('TANK', NONE))
    .addAffinityVector(new AffinityVector('MELEE_DPS', NONE))
    .addAffinityVector(new AffinityVector('RANGED_DPS', NONE))
    .addAffinityVector(new AffinityVector('CASTER_DPS', NONE))
    .addAffinityVector(new AffinityVector('SUPPORT', NONE))
    .addAffinityVector(new AffinityVector('POWER', NONE))
    .addAffinityVector(new AffinityVector('UNIQUENESS', NONE))
    .addAffinityVector(new AffinityVector('EXPERT', NONE))
    .addAffinityVector(new AffinityVector('VERSATILITY', NONE))
    .addAffinityVector(new AffinityVector('MULTICLASS', NONE))
    .addAffinityVector(new AffinityVector('NIMBLE', NONE))
    .addAffinityVector(new AffinityVector('STALWART', NONE))
    .addAffinityVector(new AffinityVector('FIELD', NONE))
    .addAffinityVector(new AffinityVector('MAGIC', NONE))
    .addAffinityVector(new AffinityVector('DEFENCE', NONE))
    .addAffinityVector(new AffinityVector('NOVA', NONE))
    .addAffinityVector(new AffinityVector('BUFF', NONE))
    .addAffinityVector(new AffinityVector('DEBUFF', NONE))
    .addAffinityVector(new AffinityVector('HEAL', NONE))
    .addAffinityVector(new AffinityVector('SHIELD', NONE))
    .addAffinityVector(new AffinityVector('SAVE', NONE))
    .build()
);

potentialCharacters.push(
    new CharacterBuilder()
    .setBuildName('')
    .setMainClass('')
    .setSubClass('')
    .setLevels(10)
    .setMultiClass('')
    .setMultiClassSubClass('')
    .setMultiClassLevels(6)
    .setHasPlaytestMaterial(false)
    .setHasHomebrewMaterial(false)
    .setNarritiveDescription('')
    .setMainClassGameplayDescription('')
    .setOtherNotes('')
    .addAffinityVector(new AffinityVector('TANK', NONE))
    .addAffinityVector(new AffinityVector('MELEE_DPS', NONE))
    .addAffinityVector(new AffinityVector('RANGED_DPS', NONE))
    .addAffinityVector(new AffinityVector('CASTER_DPS', NONE))
    .addAffinityVector(new AffinityVector('SUPPORT', NONE))
    .addAffinityVector(new AffinityVector('POWER', NONE))
    .addAffinityVector(new AffinityVector('UNIQUENESS', NONE))
    .addAffinityVector(new AffinityVector('EXPERT', NONE))
    .addAffinityVector(new AffinityVector('VERSATILITY', NONE))
    .addAffinityVector(new AffinityVector('MULTICLASS', NONE))
    .addAffinityVector(new AffinityVector('NIMBLE', NONE))
    .addAffinityVector(new AffinityVector('STALWART', NONE))
    .addAffinityVector(new AffinityVector('FIELD', NONE))
    .addAffinityVector(new AffinityVector('MAGIC', NONE))
    .addAffinityVector(new AffinityVector('DEFENCE', NONE))
    .addAffinityVector(new AffinityVector('NOVA', NONE))
    .addAffinityVector(new AffinityVector('BUFF', NONE))
    .addAffinityVector(new AffinityVector('DEBUFF', NONE))
    .addAffinityVector(new AffinityVector('HEAL', NONE))
    .addAffinityVector(new AffinityVector('SHIELD', NONE))
    .addAffinityVector(new AffinityVector('SAVE', NONE))
    .build()
);