import { CharacterBuilder } from '../Character.js';
import { AffinityVector } from '../AffinityVector.js';
import { item, spell } from '../links.js';
export let potentialCharacters = []

let OTP = 20;
let CRITICAL = 15;
let VERY = 10;
let SOME = 5;
let NONE = 0;
let NEGATIVE = -5;
let VERY_NEGATIVE = -10;


potentialCharacters.push(
    new CharacterBuilder()
    .setBuildName('The Dancer')
    .setMainClass('Bard')
    .setSubClass('College of Dance')
    .setLevels(11)
    .setMultiClass('Monk')
    .setMultiClassSubClass('Warrior of Mercy')
    .setMultiClassLevels(5)
    .setHasPlaytestMaterial(true)
    .setHasHomebrewMaterial(false)
    .setNarritiveDescription('You are as nimble as they come. In combat you are seen weaving through the battlefield with unparalleled speed. One moment healing your wounded backline and the next unleashing a flurry of blows upon the backline of the enemy. As you move your voice rises in an inspiring chant, encouraging your comrades and boosting their morale. Your bardic magic filling the air. Your allies are invincible with you by their side and your enemies fall at your hands. All this, and you don\'t even wield weapons or armor, it just wouldn\'t be fair.')
    .setMainClassGameplayDescription('Your core gameplay loop revolves around Agile Strikes and Font of Inspiration. Font of Inspiration allows you to use Bardic Inspiration every turn without running out of uses while Agile Strikes allows these Bardic Inspiration uses to also grant you a free unarmed attack. Using your bardic inspiration as a bonus action every turn will allow you to constantly hand out the die while also dishing out punches to the enemies, all without using your action which can be saved for a powerful spell or more punches.')
    .setMultiClassGameplayDescription('Your monk levels enhance your free unarmed attacks as well as your movement: making you even more slippery and able to dash around the battle field to wherever you\'re needed.')
    .setMultiClassSubClassGameplayDescription('Your monk subclass allows you to heal with just a touch, giving you another resource for healing if you are low on spell slots. Unarmored Defense, Inspiring Movement, Tandem Footwork, and Leading Evasion allow you and your party to move quickly; making them less likely to take damage, be higher on the turn order, and to stay out of danger.')
    .setFeats('Take +2 DEX for your first two ASIs to max out your DEX. Then take the Mobile feat to further enhance your movement and to make it easier to get in and out of combat. At 12th level Bard you will get another ASI which I would use to take the Inspiring Leader feat to give your party even more temporary hit points. Instead of Inspiring Leader or Mobile you could also take a half-feat that gives +1 CHA and a small bonus, such as Actor or Diplomat and/or take the +2 CHA/WIS ASI if you feel like your bard spells or stunning strikes are not landing enough.')
    .setRace('Half-Elf - The +2 CHA and +1 to two other stats (WIS/DEX) is perfect for this very MAD build. You do not need the extra CHA (since it puts you at an odd number) unless you plan on taking a CHA half-feat so Human is also a good choice.')
    .setAttributes('STR: 8, DEX: 16, CON: 8, INT: 8, WIS: 16, CHA: 17')
    .setBackground('')
    .setMagicItemsByTier(0, item('Rhythm Maker\'s Drum'))
    .setMagicItemsByTier(1, item('Amulet of Health'))
    .setMagicItemsByTier(2, item('Eldritch Claw Tattoo') + ' AND ' + item('Insignia of Claws'))
    .setRecommendedSpellsByTier(1, [])
    .setRecommendedSpellsByTier(2, [])
    .setRecommendedSpellsByTier(3, [])
    .setRecommendedSpellsByTier(4, [])
    .setRecommendedSpellsNotes('')
    .setOtherNotes('')
    .addAffinityVector(new AffinityVector('TANK', NONE))
    .addAffinityVector(new AffinityVector('MELEE_DPS', VERY))
    .addAffinityVector(new AffinityVector('RANGED_DPS', NONE))
    .addAffinityVector(new AffinityVector('CASTER_DPS', NONE))
    .addAffinityVector(new AffinityVector('SUPPORT', CRITICAL))
    .addAffinityVector(new AffinityVector('POWER', SOME))
    .addAffinityVector(new AffinityVector('UNIQUENESS', SOME))
    .addAffinityVector(new AffinityVector('EXPERT', SOME))
    .addAffinityVector(new AffinityVector('VERSATILITY', SOME))
    .addAffinityVector(new AffinityVector('MULTICLASS', VERY))
    .addAffinityVector(new AffinityVector('NIMBLE', SOME))
    .addAffinityVector(new AffinityVector('STALWART', NONE))
    .addAffinityVector(new AffinityVector('FIELD', SOME))
    .addAffinityVector(new AffinityVector('MAGIC', SOME))
    .addAffinityVector(new AffinityVector('DEFENCE', SOME))
    .addAffinityVector(new AffinityVector('NOVA', NEGATIVE))
    .addAffinityVector(new AffinityVector('BUFF', VERY))
    .addAffinityVector(new AffinityVector('DEBUFF', VERY))
    .addAffinityVector(new AffinityVector('HEAL', NONE))
    .addAffinityVector(new AffinityVector('SHIELD', NONE))
    .addAffinityVector(new AffinityVector('SAVE', OTP))
    .addAffinityVector(new AffinityVector('AOE', SOME))
    .addAffinityVector(new AffinityVector('ST', VERY))
    .build()
);

potentialCharacters.push(
    new CharacterBuilder()
    .setBuildName('The Siren')
    .setMainClass('Bard')
    .setSubClass('College of Lore')
    .setLevels(15)
    .setMultiClass('Cleric')
    .setMultiClassSubClass('Peace Domain')
    .setMultiClassLevels(1)
    .setHasPlaytestMaterial(false)
    .setHasHomebrewMaterial(false)
    .setNarritiveDescription('Your words drip with power, your every syllable unnerving enemies and empowering friends.  Chanting your arcane verse you unleash the culmination of your thorough magical studies. Through a lifelong commitment to knowledge you have amassed the ability to cast almost any spell and you wield this knowledge as a weapon and a shield, your knowledge of the arcane granting you a diverse arsenal of spells to bring to bear in any combat.')
    .setMainClassGameplayDescription('Through Magical Secrets and Additional Magical Secrets, you have access to a wide variety of spells, allowing you to adapt to any situation. Your spellcasting is your primary focus, and you have amongst the largest amount of prepared spells as well as access to all spells in the game. The power and draw of this character is that the only limit to your spellcasting is your imagination.')
    .setMultiClassGameplayDescription('You have lots of additional utility from Song of Rest, Countercharm, and Peerless Skill. You can also use your Bardic Inspiration to help your allies with their saving throws.')
    .setMultiClassSubClassGameplayDescription('Your cleric dip gives you access to the Peace Domain\'s Emboldening Bond to further buff allies and medium armor proficiency to increase your survivability.')
    .setFeats('Heavily Armored, Resilient(CON), and +1 CON/+1 CHA should be your first 3 ASIs. Next level you can take Inspiring Leader or +2 CHA.')
    .setRace('Any Race works so long as you Customize Your Origin to get +2 CHA and +1 to CON. Aasimar is a good choice for the extra healing option and flight.')
    .setAttributes('STR: 8, DEX: 10, CON: 16, INT: 10, WIS: 13, CHA: 17 Move a point from WIS to STR if you have a DM (like Tyler) who doesn\'t care about multi-classing requirements. This will give you 10 STR after you take Heavily Armored.')
    .setBackground('')
    .setMagicItemsByTier(0, item('Rhythm Maker\'s Drum') + ' OR (only if you are very worried about running out of spell slots) ' + item('Staff of Healing') + ' OR ' + item('Candel of Invocation'))
    .setMagicItemsByTier(1, item('Reveler\'s Concertina'))
    .setMagicItemsByTier(2, item('Mithral Armor') + '(Plate) AND ' + item('Sentinel Shield') + ' or buy a +1 Shield in the first session and instead get ' + item('Pearl of Power'))
    .setRecommendedSpellsByTier(1, [])
    .setRecommendedSpellsByTier(2, [])
    .setRecommendedSpellsByTier(3, [])
    .setRecommendedSpellsByTier(4, [])
    .setRecommendedSpellsNotes('')
    .setOtherNotes('The Cleric dip is almost purely for medium armor proficiency and bless. The Peace Domain synergizes well with the Bard, as it gives a second bless (no concentration) which combined with normal bless and bardic inspiration gives your allies 2d4+1d12 = +11.5(average) to ability checks, attack rolls, and saving throws.')
    .addAffinityVector(new AffinityVector('TANK', NONE))
    .addAffinityVector(new AffinityVector('MELEE_DPS', NONE))
    .addAffinityVector(new AffinityVector('RANGED_DPS', NONE))
    .addAffinityVector(new AffinityVector('CASTER_DPS', VERY))
    .addAffinityVector(new AffinityVector('SUPPORT', CRITICAL))
    .addAffinityVector(new AffinityVector('POWER', SOME))
    .addAffinityVector(new AffinityVector('UNIQUENESS', NONE))
    .addAffinityVector(new AffinityVector('EXPERT', SOME))
    .addAffinityVector(new AffinityVector('VERSATILITY', VERY))
    .addAffinityVector(new AffinityVector('MULTICLASS', VERY_NEGATIVE))
    .addAffinityVector(new AffinityVector('NIMBLE', NONE))
    .addAffinityVector(new AffinityVector('STALWART', NONE))
    .addAffinityVector(new AffinityVector('FIELD', NONE))
    .addAffinityVector(new AffinityVector('MAGIC', VERY))
    .addAffinityVector(new AffinityVector('DEFENCE', NEGATIVE))
    .addAffinityVector(new AffinityVector('NOVA', SOME))
    .addAffinityVector(new AffinityVector('BUFF', OTP))
    .addAffinityVector(new AffinityVector('DEBUFF', NONE))
    .addAffinityVector(new AffinityVector('HEAL', SOME))
    .addAffinityVector(new AffinityVector('SHIELD', NONE))
    .addAffinityVector(new AffinityVector('SAVE', CRITICAL))
    .addAffinityVector(new AffinityVector('AOE', VERY))
    .addAffinityVector(new AffinityVector('ST', SOME))
    .build()
);

potentialCharacters.push(
    new CharacterBuilder()
    .setBuildName('The Psyknife')
    .setMainClass('Rogue')
    .setSubClass('Soulknife')
    .setLevels(9)
    .setMultiClass('Fighter')
    .setMultiClassSubClass('Psi Warrior')
    .setMultiClassLevels(7)
    .setHasPlaytestMaterial(false)
    .setHasHomebrewMaterial(false)
    .setNarritiveDescription('')
    .setMainClassGameplayDescription('')
    .setMultiClassGameplayDescription('')
    .setMultiClassSubClassGameplayDescription('')
    .setFeats('Telekinetic, Telepathic, +2 DEX')
    .setRace('Gem Dragonborn')
    .setAttributes('')
    .setBackground('')
    .setMagicItemsByTier(0, 'Beg your DM or Artificer for a returning dagger. Otherwise you will be feeling bad throwing non-magical daggers all the time.')
    .setMagicItemsByTier(1, item(''))
    .setMagicItemsByTier(2, item(''))
    .addAffinityVector(new AffinityVector('TANK', NONE))
    .addAffinityVector(new AffinityVector('MELEE_DPS', VERY))
    .addAffinityVector(new AffinityVector('RANGED_DPS', CRITICAL))
    .addAffinityVector(new AffinityVector('CASTER_DPS', NONE))
    .addAffinityVector(new AffinityVector('SUPPORT', NONE))
    .addAffinityVector(new AffinityVector('POWER', VERY))
    .addAffinityVector(new AffinityVector('UNIQUENESS', NONE))
    .addAffinityVector(new AffinityVector('EXPERT', SOME))
    .addAffinityVector(new AffinityVector('VERSATILITY', NONE))
    .addAffinityVector(new AffinityVector('MULTICLASS', VERY))
    .addAffinityVector(new AffinityVector('NIMBLE', SOME))
    .addAffinityVector(new AffinityVector('STALWART', NONE))
    .addAffinityVector(new AffinityVector('FIELD', SOME))
    .addAffinityVector(new AffinityVector('MAGIC', NONE))
    .addAffinityVector(new AffinityVector('DEFENCE', NEGATIVE))
    .addAffinityVector(new AffinityVector('NOVA', NEGATIVE))
    .addAffinityVector(new AffinityVector('BUFF', NONE))
    .addAffinityVector(new AffinityVector('DEBUFF', NONE))
    .addAffinityVector(new AffinityVector('HEAL', NONE))
    .addAffinityVector(new AffinityVector('SHIELD', NONE))
    .addAffinityVector(new AffinityVector('SAVE', NONE))
    .addAffinityVector(new AffinityVector('AOE', NONE))
    .addAffinityVector(new AffinityVector('ST', CRITICAL))
    .build()
);

potentialCharacters.push(
    new CharacterBuilder()
    .setBuildName('The Crusader of the Light')
    .setMainClass('Bard')
    .setSubClass('College of Valor')
    .setLevels(10)
    .setMultiClass('Paladin')
    .setMultiClassSubClass('Oath of Devotion')
    .setMultiClassLevels(6)
    .setHasPlaytestMaterial(true)
    .setHasHomebrewMaterial(false)
    .setNarritiveDescription('You have an Oath of Devotion and went to the College of Valor. You are a goodie two shoes. There is not much more to say.')
    .setMainClassGameplayDescription('')
    .setMultiClassGameplayDescription('')
    .setMultiClassSubClassGameplayDescription('')
    .setFeats('')
    .setRace('')
    .setAttributes('')
    .setBackground('')
    .setMagicItemsByTier(0, 'Ask your DM if you can have BOTH these (and maybe even use both of their bonus actions in a single turn) ' + item('Dancing Sword') + ' and ' + item('Animated Shield') + ' otherwise just PYF Very Rare weapon.')
    .setMagicItemsByTier(1, item(''))
    .setMagicItemsByTier(2, item(''))
    .setRecommendedSpellsByTier(1, [])
    .setRecommendedSpellsByTier(2, [])
    .setRecommendedSpellsByTier(3, [])
    .setRecommendedSpellsByTier(4, [])
    .setRecommendedSpellsNotes('')
    .setOtherNotes('We already have two paladins so I\'m not sure if we need another one. Regardless, take Paladin as your first level for heavy armor proficiency.')
    .addAffinityVector(new AffinityVector('TANK', NONE))
    .addAffinityVector(new AffinityVector('MELEE_DPS', VERY))
    .addAffinityVector(new AffinityVector('RANGED_DPS', NONE))
    .addAffinityVector(new AffinityVector('CASTER_DPS', NONE))
    .addAffinityVector(new AffinityVector('SUPPORT', CRITICAL))
    .addAffinityVector(new AffinityVector('POWER', VERY))
    .addAffinityVector(new AffinityVector('UNIQUENESS', NEGATIVE))
    .addAffinityVector(new AffinityVector('EXPERT', NONE))
    .addAffinityVector(new AffinityVector('VERSATILITY', SOME))
    .addAffinityVector(new AffinityVector('MULTICLASS', VERY))
    .addAffinityVector(new AffinityVector('NIMBLE', NONE))
    .addAffinityVector(new AffinityVector('STALWART', SOME))
    .addAffinityVector(new AffinityVector('FIELD', SOME))
    .addAffinityVector(new AffinityVector('MAGIC', SOME))
    .addAffinityVector(new AffinityVector('DEFENCE', VERY))
    .addAffinityVector(new AffinityVector('NOVA', SOME))
    .addAffinityVector(new AffinityVector('BUFF', CRITICAL))
    .addAffinityVector(new AffinityVector('DEBUFF', SOME))
    .addAffinityVector(new AffinityVector('HEAL', SOME))
    .addAffinityVector(new AffinityVector('SHIELD', NONE))
    .addAffinityVector(new AffinityVector('SAVE', CRITICAL))
    .addAffinityVector(new AffinityVector('AOE', CRITICAL))
    .addAffinityVector(new AffinityVector('ST', NONE))
    .build()
);

potentialCharacters.push(
    new CharacterBuilder()
    .setBuildName('The Arcane Archer')
    .setMainClass('Fighter')
    .setSubClass('Arcane Archer')
    .setLevels(11)
    .setMultiClass('Sorcerer')
    .setMultiClassSubClass('Wild Magic')
    .setMultiClassLevels(5)
    .setHasPlaytestMaterial(false)
    .setHasHomebrewMaterial(false)
    .setNarritiveDescription('')
    .setMainClassGameplayDescription('')
    .setMultiClassGameplayDescription('')
    .setMultiClassSubClassGameplayDescription('')
    .setFeats('Sharpshooter, Magic Initiate to snag Faerie Fire, and +2 DEX')
    .setRace('Eladrin')
    .setAttributes('')
    .setBackground('')
    .setMagicItemsByTier(0, item(''))
    .setMagicItemsByTier(1, item(''))
    .setMagicItemsByTier(2, item(''))
    .setRecommendedSpellsByTier(1, [])
    .setRecommendedSpellsByTier(2, [])
    .setRecommendedSpellsByTier(3, [])
    .setRecommendedSpellsByTier(4, [])
    .setRecommendedSpellsNotes('')
    .setOtherNotes('')
    .addAffinityVector(new AffinityVector('TANK', NONE))
    .addAffinityVector(new AffinityVector('MELEE_DPS', NONE))
    .addAffinityVector(new AffinityVector('RANGED_DPS', CRITICAL))
    .addAffinityVector(new AffinityVector('CASTER_DPS', VERY))
    .addAffinityVector(new AffinityVector('SUPPORT', NONE))
    .addAffinityVector(new AffinityVector('POWER', SOME))
    .addAffinityVector(new AffinityVector('UNIQUENESS', SOME))
    .addAffinityVector(new AffinityVector('EXPERT', NONE))
    .addAffinityVector(new AffinityVector('VERSATILITY', NONE))
    .addAffinityVector(new AffinityVector('MULTICLASS', VERY))
    .addAffinityVector(new AffinityVector('NIMBLE', SOME))
    .addAffinityVector(new AffinityVector('STALWART', NONE))
    .addAffinityVector(new AffinityVector('FIELD', SOME))
    .addAffinityVector(new AffinityVector('MAGIC', NONE))
    .addAffinityVector(new AffinityVector('DEFENCE', NEGATIVE))
    .addAffinityVector(new AffinityVector('NOVA', NEGATIVE))
    .addAffinityVector(new AffinityVector('BUFF', NONE))
    .addAffinityVector(new AffinityVector('DEBUFF', NONE))
    .addAffinityVector(new AffinityVector('HEAL', NONE))
    .addAffinityVector(new AffinityVector('SHIELD', NONE))
    .addAffinityVector(new AffinityVector('SAVE', NONE))
    .addAffinityVector(new AffinityVector('AOE', SOME))
    .addAffinityVector(new AffinityVector('ST', VERY))
    .build()
);

potentialCharacters.push(
    new CharacterBuilder()
    .setBuildName('The Lich King')
    .setMainClass('Warlock')
    .setSubClass('The Undying')
    .setLevels(11)
    .setMultiClass('Paladin')
    .setMultiClassSubClass('Oath of Vengeance')
    .setMultiClassLevels(5)
    .setHasPlaytestMaterial(true)
    .setHasHomebrewMaterial(false)
    .setNarritiveDescription('')
    .setMainClassGameplayDescription('')
    .setMultiClassGameplayDescription('')
    .setMultiClassSubClassGameplayDescription('')
    .setFeats('Mounted Combatant, Elven Accuracy, +2 CHA')
    .setRace('Elf')
    .setAttributes('')
    .setBackground('')
    .setMagicItemsByTier(0, item('Dragon\'s Wrath Weapon'))
    .setMagicItemsByTier(1, item('Butcher\'s Bib'))
    .setMagicItemsByTier(2, item('Saddle of the Cavalier') + ' AND ' + item('Gauntlets of Ogre Power'))
    .setRecommendedSpellsByTier(1, [])
    .setRecommendedSpellsByTier(2, [])
    .setRecommendedSpellsByTier(3, [])
    .setRecommendedSpellsByTier(4, [])
    .setRecommendedSpellsNotes('')
    .setOtherNotes('')
    .addAffinityVector(new AffinityVector('TANK', NONE))
    .addAffinityVector(new AffinityVector('MELEE_DPS', CRITICAL))
    .addAffinityVector(new AffinityVector('RANGED_DPS', NONE))
    .addAffinityVector(new AffinityVector('CASTER_DPS', VERY))
    .addAffinityVector(new AffinityVector('SUPPORT', NONE))
    .addAffinityVector(new AffinityVector('POWER', SOME))
    .addAffinityVector(new AffinityVector('UNIQUENESS', SOME))
    .addAffinityVector(new AffinityVector('EXPERT', NONE))
    .addAffinityVector(new AffinityVector('VERSATILITY', NEGATIVE))
    .addAffinityVector(new AffinityVector('MULTICLASS', SOME))
    .addAffinityVector(new AffinityVector('NIMBLE', NONE))
    .addAffinityVector(new AffinityVector('STALWART', SOME))
    .addAffinityVector(new AffinityVector('FIELD', SOME))
    .addAffinityVector(new AffinityVector('MAGIC', NONE))
    .addAffinityVector(new AffinityVector('DEFENCE', NEGATIVE))
    .addAffinityVector(new AffinityVector('NOVA', VERY))
    .addAffinityVector(new AffinityVector('BUFF', NONE))
    .addAffinityVector(new AffinityVector('DEBUFF', NONE))
    .addAffinityVector(new AffinityVector('HEAL', NONE))
    .addAffinityVector(new AffinityVector('SHIELD', NONE))
    .addAffinityVector(new AffinityVector('SAVE', NONE))
    .addAffinityVector(new AffinityVector('AOE', NONE))
    .addAffinityVector(new AffinityVector('ST', CRITICAL))
    .build()
);

potentialCharacters.push(
    new CharacterBuilder()
    .setBuildName('The Healbot')
    .setMainClass('Cleric')
    .setSubClass('Life Domain')
    .setLevels(6)
    .setMultiClass('Druid')
    .setMultiClassSubClass('Circle of Stars')
    .setMultiClassLevels(10)
    .setHasPlaytestMaterial(false)
    .setHasHomebrewMaterial(false)
    .setNarritiveDescription('None can match your healing prowess. Your philosophy is that the best support is the one that heals for the biggest number. You have studied both amongsth the clerics and the druids, taking only the information that would allow you to heal the most. Your lifelong goal is to find an enemy who can actually test your healing abilities. You have yet to find one.')
    .setMainClassGameplayDescription('')
    .setMultiClassGameplayDescription('')
    .setMultiClassSubClassGameplayDescription('')
    .setFeats('Gift of the Gem Dragon (or any WIS half-feat) and +2 WIS for your first two gets you to 20 WIS. For your third ASI I recommend Tough although proficiency for CON saves through a feat will cut down on how often you are recasting your concentration spells. Note the focus on HP and CON is so that you can cast all of your healing spells on allies and slowly heal yourself up through the contstant self healing from Blessed Healer.')
    .setRace('Tasha\'s Custom Lineage: +2 WIS and the Inspiring Leader feat.')
    .setAttributes('STR: 8, DEX: 14, CON: 8, INT: 12, WIS: 17, CHA: 14')
    .setBackground('')
    .setMagicItemsByTier(0, item('Candle of Invocation'))
    .setMagicItemsByTier(1, item('Amulet of Health'))
    .setMagicItemsByTier(2, item('Mithral Armor') + '(plate) AND ' + item('Moon Sickle'))
    .setRecommendedSpellsByTier(1, [])
    .setRecommendedSpellsByTier(2, [])
    .setRecommendedSpellsByTier(3, [])
    .setRecommendedSpellsByTier(4, [])
    .setRecommendedSpellsNotes('')
    .setOtherNotes('This character is a healbot and is optimized as such. Be warned, against enemies of your level, cantrips or spells that you use on enemies will often result in the enemy dodging or saving against your spells. Focus on healing and buffing allies, which is where you shine and much more difficult for enemies to prevent.')
    .addAffinityVector(new AffinityVector('TANK', NONE))
    .addAffinityVector(new AffinityVector('MELEE_DPS', NONE))
    .addAffinityVector(new AffinityVector('RANGED_DPS', NONE))
    .addAffinityVector(new AffinityVector('CASTER_DPS', SOME))
    .addAffinityVector(new AffinityVector('SUPPORT', OTP))
    .addAffinityVector(new AffinityVector('POWER', SOME))
    .addAffinityVector(new AffinityVector('UNIQUENESS', NONE))
    .addAffinityVector(new AffinityVector('EXPERT', NONE))
    .addAffinityVector(new AffinityVector('VERSATILITY', NONE))
    .addAffinityVector(new AffinityVector('MULTICLASS', SOME))
    .addAffinityVector(new AffinityVector('NIMBLE', NONE))
    .addAffinityVector(new AffinityVector('STALWART', NONE))
    .addAffinityVector(new AffinityVector('FIELD', SOME))
    .addAffinityVector(new AffinityVector('MAGIC', VERY))
    .addAffinityVector(new AffinityVector('DEFENCE', SOME))
    .addAffinityVector(new AffinityVector('NOVA', SOME))
    .addAffinityVector(new AffinityVector('BUFF', SOME))
    .addAffinityVector(new AffinityVector('DEBUFF', SOME))
    .addAffinityVector(new AffinityVector('HEAL', OTP))
    .addAffinityVector(new AffinityVector('SHIELD', SOME))
    .addAffinityVector(new AffinityVector('SAVE', SOME))
    .addAffinityVector(new AffinityVector('AOE', SOME))
    .addAffinityVector(new AffinityVector('ST', VERY))
    .build()
);

potentialCharacters.push(
    new CharacterBuilder()
    .setBuildName('The Starry Twilight Healer')
    .setMainClass('Cleric')
    .setSubClass('Twilight Domain')
    .setLevels(6)
    .setMultiClass('Druid')
    .setMultiClassSubClass('Circle of Stars')
    .setMultiClassLevels(10)
    .setHasPlaytestMaterial(false)
    .setHasHomebrewMaterial(false)
    .setNarritiveDescription('You are a dark beacon of hope and healing to your allies. You are a master of the stars and the night, and you use your knowledge of the cosmos to heal and shield your allies. You are unmatched in your ability to keep your allies healthy, choosing to focus only on support magic that increases the available health pool of your allies at the expense of all other forms of support.')
    .setMainClassGameplayDescription('')
    .setMultiClassGameplayDescription('')
    .setMultiClassSubClassGameplayDescription('')
    .setFeats('+1 WIS/+1 CON and +2 WIS for your first two gets you to 20 WIS. Then take Resilient(CON) to get your CON to 16.')
    .setRace('Tasha\'s Custom Lineage - +2 WIS and the Inspiring Leader feat.')
    .setAttributes('STR: 8, DEX: 12, CON: 14, INT: 10, WIS: 17, CHA: 13')
    .setBackground('')
    .setMagicItemsByTier(0, item('Candle of Invocation'))
    .setMagicItemsByTier(1, item('Staff of Healing'))
    .setMagicItemsByTier(2, item('Mithral Armor') + item('Moon Sickle'))
    .setRecommendedSpellsByTier(1, [])
    .setRecommendedSpellsByTier(2, [])
    .setRecommendedSpellsByTier(3, [])
    .setRecommendedSpellsByTier(4, [])
    .setRecommendedSpellsNotes('')
    .setOtherNotes('')
    .addAffinityVector(new AffinityVector('TANK', NONE))
    .addAffinityVector(new AffinityVector('MELEE_DPS', NONE))
    .addAffinityVector(new AffinityVector('RANGED_DPS', NONE))
    .addAffinityVector(new AffinityVector('CASTER_DPS', SOME))
    .addAffinityVector(new AffinityVector('SUPPORT', OTP))
    .addAffinityVector(new AffinityVector('POWER', SOME))
    .addAffinityVector(new AffinityVector('UNIQUENESS', NONE))
    .addAffinityVector(new AffinityVector('EXPERT', NONE))
    .addAffinityVector(new AffinityVector('VERSATILITY', NONE))
    .addAffinityVector(new AffinityVector('MULTICLASS', SOME))
    .addAffinityVector(new AffinityVector('NIMBLE', NONE))
    .addAffinityVector(new AffinityVector('STALWART', NONE))
    .addAffinityVector(new AffinityVector('FIELD', SOME))
    .addAffinityVector(new AffinityVector('MAGIC', VERY))
    .addAffinityVector(new AffinityVector('DEFENCE', SOME))
    .addAffinityVector(new AffinityVector('NOVA', SOME))
    .addAffinityVector(new AffinityVector('BUFF', SOME))
    .addAffinityVector(new AffinityVector('DEBUFF', SOME))
    .addAffinityVector(new AffinityVector('HEAL', CRITICAL))
    .addAffinityVector(new AffinityVector('SHIELD', VERY))
    .addAffinityVector(new AffinityVector('SAVE', NONE))
    .addAffinityVector(new AffinityVector('AOE', VERY))
    .addAffinityVector(new AffinityVector('ST', SOME))
    .build()
);

potentialCharacters.push(
    new CharacterBuilder()
    .setBuildName('The Burst of Light')
    .setMainClass('Cleric')
    .setSubClass('Light Domain')
    .setLevels(14)
    .setMultiClass('Fighter')
    .setMultiClassSubClass('N/A')
    .setMultiClassLevels(2)
    .setHasPlaytestMaterial(false)
    .setHasHomebrewMaterial(false)
    .setNarritiveDescription('Light flickers in your eyes, the unstable light reflected from the scene in front of you. The light brings you joy as you reflect on the righteous work you have done today. You have brought The Light to this town, the pure and unadulterated Light of your god. There is no light as pure and as powerful as The Light of your god, and you are the vessel through which it shines. You are The Light in the darkness, the beacon of hope, and the bringer of justice. You are The Light of the world. Only the pure and cleansing Light of fire can cleanse the world of the darkness that plagues it. You laugh as the fire consumes the town, The Light of your god reflected in your eyes.')
    .setMainClassGameplayDescription('')
    .setMultiClassGameplayDescription('')
    .setMultiClassSubClassGameplayDescription('')
    .setFeats('War Caster and Elemental Adept (Fire) are all good choices.')
    .setRace('')
    .setAttributes('')
    .setBackground('')
    .setMagicItemsByTier(0, item('Amulet of the Devout'))
    .setMagicItemsByTier(1, item('Ring of Spell Storing'))
    .setMagicItemsByTier(2, item('Winged Boots') + ' AND ' + item('Pearl of Power'))
    .setRecommendedSpellsByTier(1, ['Burning Hands', 'Faerie Fire', 'Guiding Bolt', 'Healing Word', 'Inflict Wounds', 'Shield of Faith'])
    .setRecommendedSpellsByTier(2, ['Flaming Sphere', 'Scorching Ray', 'Spiritual Weapon', 'Warding Bond'])
    .setRecommendedSpellsByTier(3, ['Daylight', 'Fireball', 'Revivify', 'Spirit Guardians'])
    .setRecommendedSpellsByTier(4, ['4+ Just upcast Fireball/Spirit Guardians/Spiritual Weapon(if you want damage)/Flaming Sphere(if you want to fit the theme)'])
    .setRecommendedSpellsNotes('')
    .setOtherNotes('')
    .addAffinityVector(new AffinityVector('TANK', NONE))
    .addAffinityVector(new AffinityVector('MELEE_DPS', NONE))
    .addAffinityVector(new AffinityVector('RANGED_DPS', NONE))
    .addAffinityVector(new AffinityVector('CASTER_DPS', OTP))
    .addAffinityVector(new AffinityVector('SUPPORT', SOME))
    .addAffinityVector(new AffinityVector('POWER', SOME))
    .addAffinityVector(new AffinityVector('UNIQUENESS', NONE))
    .addAffinityVector(new AffinityVector('EXPERT', NONE))
    .addAffinityVector(new AffinityVector('VERSATILITY', NONE))
    .addAffinityVector(new AffinityVector('MULTICLASS', NEGATIVE))
    .addAffinityVector(new AffinityVector('NIMBLE', NONE))
    .addAffinityVector(new AffinityVector('STALWART', NONE))
    .addAffinityVector(new AffinityVector('FIELD', SOME))
    .addAffinityVector(new AffinityVector('MAGIC', VERY))
    .addAffinityVector(new AffinityVector('DEFENCE', SOME))
    .addAffinityVector(new AffinityVector('NOVA', VERY))
    .addAffinityVector(new AffinityVector('BUFF', VERY))
    .addAffinityVector(new AffinityVector('DEBUFF', SOME))
    .addAffinityVector(new AffinityVector('HEAL', SOME))
    .addAffinityVector(new AffinityVector('SHIELD', NONE))
    .addAffinityVector(new AffinityVector('SAVE', SOME))
    .addAffinityVector(new AffinityVector('AOE', CRITICAL))
    .addAffinityVector(new AffinityVector('ST', NONE))
    .build()
);
/*
potentialCharacters.push(
    new CharacterBuilder()
    .setBuildName('')
    .setMainClass('')
    .setSubClass('')
    .setLevels(10)
    .setMultiClass('')
    .setMultiClassSubClass('')
    .setMultiClassLevels(6)
    .setHasPlaytestMaterial(false)
    .setHasHomebrewMaterial(false)
    .setNarritiveDescription('')
    .setMainClassGameplayDescription('')
    .setMultiClassGameplayDescription('')
    .setMultiClassSubClassGameplayDescription('')
    .setFeats('')
    .setRace('')
    .setAttributes('')
    .setBackground('')
    .setMagicItemsByTier(0, item(''))
    .setMagicItemsByTier(1, item(''))
    .setMagicItemsByTier(2, item(''))
    .setRecommendedSpellsByTier(1, [])
    .setRecommendedSpellsByTier(2, [])
    .setRecommendedSpellsByTier(3, [])
    .setRecommendedSpellsByTier(4, [])
    .setRecommendedSpellsByTier(5, [])
    .setRecommendedSpellsNotes('')
    .setOtherNotes('')
    .addAffinityVector(new AffinityVector('TANK', NONE))
    .addAffinityVector(new AffinityVector('MELEE_DPS', NONE))
    .addAffinityVector(new AffinityVector('RANGED_DPS', NONE))
    .addAffinityVector(new AffinityVector('CASTER_DPS', NONE))
    .addAffinityVector(new AffinityVector('SUPPORT', NONE))
    .addAffinityVector(new AffinityVector('POWER', NONE))
    .addAffinityVector(new AffinityVector('UNIQUENESS', NONE))
    .addAffinityVector(new AffinityVector('EXPERT', NONE))
    .addAffinityVector(new AffinityVector('VERSATILITY', NONE))
    .addAffinityVector(new AffinityVector('MULTICLASS', NONE))
    .addAffinityVector(new AffinityVector('NIMBLE', NONE))
    .addAffinityVector(new AffinityVector('STALWART', NONE))
    .addAffinityVector(new AffinityVector('FIELD', NONE))
    .addAffinityVector(new AffinityVector('MAGIC', NONE))
    .addAffinityVector(new AffinityVector('DEFENCE', NONE))
    .addAffinityVector(new AffinityVector('NOVA', NONE))
    .addAffinityVector(new AffinityVector('BUFF', NONE))
    .addAffinityVector(new AffinityVector('DEBUFF', NONE))
    .addAffinityVector(new AffinityVector('HEAL', NONE))
    .addAffinityVector(new AffinityVector('SHIELD', NONE))
    .addAffinityVector(new AffinityVector('SAVE', NONE))
    .addAffinityVector(new AffinityVector('AOE', NONE))
    .addAffinityVector(new AffinityVector('ST', NONE))
    .build()
);
*/